name: Label Handler
description: Executes label-triggered behaviors (pin, unpin) via GraphQL

inputs:
    action:
        description: 'Label event: labeled or unlabeled'
        required: true
    label:
        description: 'Label name that triggered the event'
        required: true
    node_id:
        description: 'Issue/PR node_id for GraphQL mutations'
        required: true
    number:
        description: 'Issue/PR number'
        required: true

outputs:
    executed:
        description: 'Whether a behavior was executed'
        value: ${{ steps.run.outputs.executed }}

runs:
    using: composite
    steps:
        - name: Execute Label Behavior
          id: run
          uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
          with:
              script: |
                  const action = '${{ inputs.action }}';
                  const label = '${{ inputs.label }}';
                  const nodeId = '${{ inputs.node_id }}';
                  const number = parseInt('${{ inputs.number }}');

                  // Label behaviors config (mirroring B.labels.behaviors from schema.ts)
                  const behaviors = {
                      pinned: { onAdd: 'pin', onRemove: 'unpin' },
                  };

                  // GraphQL mutations (mirroring B.labels.gql from schema.ts)
                  const gql = {
                      pin: `mutation($issueId:ID!){pinIssue(input:{issueId:$issueId}){issue{id}}}`,
                      unpin: `mutation($issueId:ID!){unpinIssue(input:{issueId:$issueId}){issue{id}}}`,
                  };

                  // Resolve behavior from label + action
                  const behaviorKey = action === 'labeled' ? 'onAdd' : 'onRemove';
                  const behavior = behaviors[label]?.[behaviorKey];

                  if (behavior && gql[behavior]) {
                      try {
                          await github.graphql(gql[behavior], { issueId: nodeId });
                          core.info(`[OK] Issue #${number} ${behavior}ned successfully`);
                          core.setOutput('executed', true);
                      } catch (error) {
                          core.warning(`Could not ${behavior} issue: ${error.message}`);
                          core.setOutput('executed', false);
                      }
                  } else {
                      core.info(`[LABEL] ${label} ${action}: no-op`);
                      core.setOutput('executed', false);
                  }
