name: Changed Detection
description: Detect changed files and affected Nx projects with three detection modes (fast|comprehensive|matrix)

inputs:
    mode:
        description: Detection mode - fast (Git API), comprehensive (REST API), or matrix (parallel matrix generation)
        required: false
        default: 'fast'
    files_pattern:
        description: File pattern for changed-files action (e.g., '**.ts|**.tsx')
        required: false
        default: ''
    globs_pattern:
        description: Glob patterns to filter changed files (comma-separated, e.g., 'apps/**,packages/**')
        required: false
        default: ''
    base_sha:
        description: Base SHA for comparison (overrides nx-set-shas base)
        required: false
        default: ''

outputs:
    changed_files:
        description: JSON array of changed file paths
        value: ${{ steps.run.outputs.changed_files }}
    affected_projects:
        description: JSON array of affected Nx project names
        value: ${{ steps.run.outputs.affected_projects }}
    stats_json:
        description: JSON object with change statistics (added, modified, deleted counts)
        value: ${{ steps.run.outputs.stats_json }}
    matrix_json:
        description: JSON matrix configuration for parallel jobs (matrix mode only)
        value: ${{ steps.run.outputs.matrix_json }}
    has_changes:
        description: Boolean indicating if any changes were detected
        value: ${{ steps.run.outputs.has_changes }}

runs:
    using: composite
    steps:
        # Use step-security/changed-files for secure file detection
        - name: Detect Changed Files
          id: changed-files
          uses: step-security/changed-files@f9b3bb1f9126ed32d88ef4aacec02bde4b70daa2 # v4.3.0
          with:
              # Use files_pattern if provided, otherwise detect all changes
              files: ${{ inputs.files_pattern || '**' }}
              # Output format optimized for JSON processing
              json: true
              # Include file status (added, modified, deleted)
              write_output_files: false

        # Run algorithmic change detection script
        - name: Process Changes
          id: run
          uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
          env:
              NODE_OPTIONS: --import tsx
              CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              MODE: ${{ inputs.mode }}
              GLOBS_PATTERN: ${{ inputs.globs_pattern }}
              BASE_SHA: ${{ inputs.base_sha }}
          with:
              script: |
                  const { run } = await import('${{ github.workspace }}/.github/scripts/changed-detection.ts');
                  const result = await run({
                      context: { repo: context.repo, payload: context.payload, sha: context.sha },
                      core,
                      github,
                      env: {
                          changedFiles: process.env.CHANGED_FILES || '[]',
                          mode: process.env.MODE || 'fast',
                          globsPattern: process.env.GLOBS_PATTERN || '',
                          baseSha: process.env.BASE_SHA || '',
                          headSha: process.env.HEAD_SHA || '',
                      },
                  });
                  
                  // Set outputs
                  core.setOutput('changed_files', JSON.stringify(result.changedFiles));
                  core.setOutput('affected_projects', JSON.stringify(result.affectedProjects));
                  core.setOutput('stats_json', JSON.stringify(result.stats));
                  core.setOutput('matrix_json', JSON.stringify(result.matrix));
                  core.setOutput('has_changes', String(result.hasChanges));
                  
                  // Summary
                  core.info(`✓ Detection mode: ${result.mode}`);
                  core.info(`✓ Changed files: ${result.changedFiles.length}`);
                  core.info(`✓ Affected projects: ${result.affectedProjects.length}`);
