# --- TLS CERTIFICATE ----------------------------------------------------------
# Automated TLS certificate via cert-manager Let's Encrypt
# Certificate will be stored in Secret: parametric-portal-tls
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: parametric-portal-tls
  namespace: parametric-portal
  labels:
    app.kubernetes.io/name: parametric-portal
    app.kubernetes.io/component: tls
spec:
  secretName: parametric-portal-tls

  # --- [ISSUER] --------------------------------------------------------------
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  # --- [DOMAINS] -------------------------------------------------------------
  # Primary domain + wildcard for subdomains
  dnsNames:
    - "parametric-portal.com"
    - "*.parametric-portal.com"

  # --- [PRIVATE_KEY] ---------------------------------------------------------
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always

  # --- [USAGES] --------------------------------------------------------------
  usages:
    - digital signature
    - key encipherment
    - server auth

  # --- [RENEWAL] -------------------------------------------------------------
  # Auto-renew 30 days before expiration (Let's Encrypt default: 90-day validity)
  renewBefore: 720h
