# --- LETSENCRYPT CLUSTERISSUER (AZURE DNS) -----------------------------------
# DNS-01 challenge solver for wildcard and custom domain certificates
# Requires: Azure managed identity or service principal with DNS Zone Contributor
#
# [IMPORTANT] Configuration values below are non-sensitive Azure identifiers
# Replace placeholders with actual values via:
#   1. Kustomize patches in environment overlays
#   2. ArgoCD valueFiles
#   3. ConfigMap + Kustomize replacements
#
# Azure values are NOT secrets - they are public Azure resource identifiers
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: letsencrypt
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: platform
  annotations:
    parametric-portal.com/config-source: "placeholder"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # [REPLACE] Admin email for certificate expiry notifications
    email: admin@parametric-portal.com
    privateKeySecretRef:
      name: letsencrypt-prod-key

    solvers:
      - dns01:
          azureDNS:
            # [REPLACE] Azure subscription ID (UUID)
            subscriptionID: "00000000-0000-0000-0000-000000000000"
            # [REPLACE] Resource group containing DNS zone
            resourceGroupName: "parametric-portal-rg"
            # [REPLACE] DNS zone name
            hostedZoneName: "parametric-portal.com"
            environment: AzurePublicCloud
            managedIdentity:
              # [REPLACE] Managed identity client ID for DNS access
              clientID: "00000000-0000-0000-0000-000000000000"
---
# --- LETSENCRYPT STAGING (FOR TESTING) ---------------------------------------
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: letsencrypt
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: platform
  annotations:
    parametric-portal.com/config-source: "placeholder"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@parametric-portal.com
    privateKeySecretRef:
      name: letsencrypt-staging-key

    solvers:
      - dns01:
          azureDNS:
            subscriptionID: "00000000-0000-0000-0000-000000000000"
            resourceGroupName: "parametric-portal-rg"
            hostedZoneName: "parametric-portal.com"
            environment: AzurePublicCloud
            managedIdentity:
              clientID: "00000000-0000-0000-0000-000000000000"
