# --- Commit Type Labels ------------------------------------------------------

- name: fix
  color: "f05223"
  description: "Bug fix"

- name: feat
  color: "0969da"
  description: "New feature request"

- name: docs
  color: "0067a6"
  description: "Improvements or additions to documentation"

- name: style
  color: "6c3082"
  description: "Formatting, no logic change"

- name: refactor
  color: "3a140e"
  description: "Code restructuring without behavior change"

- name: test
  color: "6f4f38"
  description: "Adding or updating tests"

- name: chore
  color: "c4b091"
  description: "Maintenance task"

- name: perf
  color: "9aca3c"
  description: "Performance improvement"

- name: ci
  color: "650e3d"
  description: "CI/CD pipeline changes"

- name: build
  color: "93c572"
  description: "Build system or tooling"

# --- Issue-Only Type Labels (no commit prefix) -------------------------------

- name: help
  color: "702963"
  description: "Question or assistance needed"

# --- Priority Labels ---------------------------------------------------------

- name: critical
  color: "ff473e"
  description: "Must be addressed immediately"

# --- Action Labels -----------------------------------------------------------

- name: implement
  color: "ee3a95"
  description: "Ready for implementation"

- name: review
  color: "FFF58A"
  description: "Needs review"

- name: blocked
  color: "fed700"
  description: "Cannot proceed"

# --- Agent Labels (Mutually Exclusive) ---------------------------------------

- name: copilot
  color: "848482"
  description: "Assign to GitHub Copilot"

- name: claude
  color: "848482"
  description: "Assign to Claude"

- name: gemini
  color: "848482"
  description: "Assign to Gemini"

- name: codex
  color: "848482"
  description: "Assign to OpenAI Codex"

# --- Lifecycle Labels --------------------------------------------------------

- name: stale
  color: "2a3439"
  description: "No recent activity"

- name: pinned
  color: "123524"
  description: "Exempt from stale"

# --- Special Labels ----------------------------------------------------------

- name: security
  color: "FF2DD1"
  description: "Security issue"

- name: dependencies
  color: "1D2952"
  description: "Dependency updates (bot-applied)"

- name: breaking
  color: "701c1c"
  description: "Breaking change"

- name: dashboard
  color: "00a693"
  description: "Repository metrics dashboard"
