# --- Commit Type Labels (PR/Commit Correlation) ------------------------------

- name: fix
  color: "f05223"
  description: "Bug fix"

- name: feat
  color: "0969da"
  description: "New feature request"

- name: docs
  color: "0067a6"
  description: "Improvements or additions to documentation"

- name: style
  color: "6c3082"
  description: "Formatting, no logic change"

- name: refactor
  color: "3a140e"
  description: "Code restructuring without behavior change"

- name: test
  color: "6f4f38"
  description: "Adding or updating tests"

- name: chore
  color: "c4b091"
  description: "Maintenance task"

- name: perf
  color: "9aca3c"
  description: "Performance improvement"

- name: ci
  color: "650e3d"
  description: "CI/CD pipeline changes"

- name: build
  color: "93c572"
  description: "Build system or tooling"

# --- Issue-Only Type Labels (no commit prefix) --------------------------------

- name: help
  color: "702963"
  description: "Question or assistance needed"

# --- Kind Axis (Agentic: Work Unit Type) --------------------------------------

- name: kind:project
  color: "8b5cf6"
  description: "Top-level initiative (e.g., Agentic Framework)"

- name: kind:task
  color: "3b82f6"
  description: "Default work unit leading to code changes"

- name: kind:spike
  color: "06b6d4"
  description: "Research task with knowledge outputs"

- name: kind:refactor
  color: "3a140e"
  description: "Code restructuring without behavior change"

# --- Status Axis (Agentic: Current State) -------------------------------------

- name: status:triage
  color: "9ca3af"
  description: "Newly created, not yet shaped"

- name: status:implement
  color: "ee3a95"
  description: "Ready for implementation by AI/human"

- name: status:in-progress
  color: "fbbf24"
  description: "Someone (agent or human) is working"

- name: status:review
  color: "FFF58A"
  description: "Needs review"

- name: status:blocked
  color: "fed700"
  description: "Cannot proceed"

- name: status:done
  color: "10b981"
  description: "Completed and merged"

- name: status:idea
  color: "e5e7eb"
  description: "Untriaged raw input"

- name: status:planning
  color: "c7d2fe"
  description: "Being shaped into a plan"

# --- Phase Axis (Agentic: Project Lifecycle) ----------------------------------

- name: phase:0-foundation
  color: "1e293b"
  description: "Phase 0: Foundation work"

- name: phase:1-planning
  color: "475569"
  description: "Phase 1: Planning"

- name: phase:2-impl-core
  color: "64748b"
  description: "Phase 2: Core implementation"

- name: phase:3-impl-extensions
  color: "94a3b8"
  description: "Phase 3: Extensions implementation"

- name: phase:4-hardening
  color: "cbd5e1"
  description: "Phase 4: Hardening and stabilization"

- name: phase:5-release
  color: "f1f5f9"
  description: "Phase 5: Release preparation"

# --- Priority Axis (Agentic: Urgency) -----------------------------------------

- name: priority:critical
  color: "ff473e"
  description: "Must be addressed immediately"

- name: priority:high
  color: "fb923c"
  description: "High priority"

- name: priority:medium
  color: "fcd34d"
  description: "Medium priority"

- name: priority:low
  color: "d4d4d8"
  description: "Low priority"

# --- Agent Labels (Mutually Exclusive) ----------------------------------------

- name: copilot
  color: "848482"
  description: "Assign to GitHub Copilot"

- name: claude
  color: "848482"
  description: "Assign to Claude"

- name: gemini
  color: "848482"
  description: "Assign to Gemini"

- name: codex
  color: "848482"
  description: "Assign to OpenAI Codex"

# --- Lifecycle Labels ---------------------------------------------------------

- name: stale
  color: "2a3439"
  description: "No recent activity"

- name: pinned
  color: "123524"
  description: "Exempt from stale"

# --- Special Labels -----------------------------------------------------------

- name: security
  color: "FF2DD1"
  description: "Security issue"

- name: dependencies
  color: "1D2952"
  description: "Dependency updates (bot-applied)"

- name: breaking
  color: "701c1c"
  description: "Breaking change"

- name: dashboard
  color: "00a693"
  description: "Repository metrics dashboard"