# Parametric Portal - Label Definitions

# --- Type Labels -------------------------------------------------------------
- name: bug
  color: "d73a4a"                       # red
  description: "Something isn't working"

- name: feature
  color: "a2eeef"                       # cyan
  description: "New feature request"

- name: docs
  color: "0075ca"                       # blue
  description: "Documentation only"

- name: chore
  color: "d4a373"                       # tan
  description: "Maintenance task"

- name: refactor
  color: "fbca04"                       # yellow
  description: "Code restructuring without behavior change"

- name: help
  color: "d876e3"                       # pink
  description: "Question or assistance needed"

- name: enhancement
  color: "84b6eb"                       # light blue
  description: "Improvement to existing feature"

# --- Priority Labels ---------------------------------------------------------
- name: critical
  color: "b60205"                       # dark red
  description: "Must be addressed immediately"

# --- Action Labels -----------------------------------------------------------
- name: implement
  color: "7057ff"                       # purple
  description: "Ready for implementation"

- name: review
  color: "e99695"                       # salmon
  description: "Needs review"

- name: blocked
  color: "b60205"                       # dark red
  description: "Cannot proceed"

# --- Agent Labels (Mutually Exclusive) ---------------------------------------
- name: copilot
  color: "8b949e"                       # grey
  description: "Assign to GitHub Copilot"

- name: claude
  color: "8b949e"                       # grey
  description: "Assign to Claude"

- name: gemini
  color: "8b949e"                       # grey
  description: "Assign to Gemini"

- name: codex
  color: "8b949e"                       # grey
  description: "Assign to OpenAI Codex"

# --- Lifecycle Labels --------------------------------------------------------
- name: stale
  color: "57606a"                       # dark grey
  description: "No recent activity"

- name: pinned
  color: "006b75"                       # teal
  description: "Exempt from stale"

# --- Quality Labels ----------------------------------------------------------
- name: needs-info
  color: "f9d0c4"                       # peach
  description: "Requires improvement before actionable"

# --- Special Labels (External Sources) ---------------------------------------
- name: security
  color: "8957e5"                       # purple
  description: "Security issue"

- name: dependencies
  color: "0550ae"                       # dark blue
  description: "Dependency updates"
