name: Setup Environment
description: Unified Node.js + pnpm setup with caching for Parametric Portal

inputs:
    node-version:
        description: Node.js version to use
        default: '25.2.1'
    pnpm-version:
        description: pnpm version to use
        default: '10.23.0'
    install-dependencies:
        description: Whether to run pnpm install
        default: 'true'

runs:
    using: composite
    steps:
        - name: Setup pnpm
          uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
          with:
              version: ${{ inputs.pnpm-version }}
              run_install: false

        - name: Setup Node.js
          uses: actions/setup-node@633bb92bc0aabcae06e8ea93b85aecddd374c402 # v4
          with:
              node-version: ${{ inputs.node-version }}
              cache: pnpm

        - name: Install Dependencies
          if: inputs.install-dependencies == 'true'
          shell: bash
          run: pnpm install --frozen-lockfile
