packages:
  - apps/*
  - infrastructure
  - packages/*
  - tests

catalog:
  '@anthropic-ai/tokenizer': 0.0.4
  '@aws-sdk/client-s3': 3.991.0
  '@aws-sdk/client-sesv2': 3.991.0
  '@aws-sdk/s3-request-presigner': 3.991.0
  '@berenddeboer/nx-biome': 1.0.2
  '@biomejs/biome': 2.4.2
  '@dopplerhq/node-sdk': 1.3.0
  '@effect-aws/client-s3': 1.10.9
  '@effect/ai': 0.33.2
  '@effect/ai-anthropic': 0.23.0
  '@effect/ai-google': 0.12.1
  '@effect/ai-openai': 0.37.2
  '@effect/cluster': 0.56.4
  '@effect/experimental': 0.58.0
  '@effect/opentelemetry': 0.61.0
  '@effect/platform': 0.94.5
  '@effect/platform-browser': 0.74.0
  '@effect/platform-node': 0.104.1
  '@effect/platform-node-shared': 0.57.1
  '@effect/rpc': 0.73.2
  '@effect/sql': 0.49.0
  '@effect/sql-pg': 0.50.3
  '@effect/vitest': 0.27.0
  '@effect/workflow': 0.16.0
  '@floating-ui/react': 0.27.18
  '@floating-ui/react-dom': 2.1.7
  '@formkit/auto-animate': 0.9.0
  '@gltf-transform/core': 4.3.0
  '@internationalized/date': 3.11.0
  '@mermaid-js/mermaid-cli': 11.12.0
  '@nx/docker': 22.5.1
  '@nx/js': 22.5.1
  '@nx/playwright': 22.5.1
  '@nx/react': 22.5.1
  '@nx/vite': 22.5.1
  '@nx/vitest': 22.5.1
  '@octokit/rest': 22.0.1
  '@playwright/test': 1.58.2
  '@pulumi/aws': 7.19.0
  '@pulumi/awsx': 3.1.0
  '@pulumi/command': 1.1.3
  '@pulumi/docker': 4.11.0
  '@pulumi/kubernetes': 4.25.0
  '@pulumi/pulumi': 3.220.0
  '@pulumi/random': 4.19.1
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-separator': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-visually-hidden': 1.2.4
  '@react-aria/live-announcer': 3.4.4
  '@rollup/plugin-typescript': 12.3.0
  '@stryker-mutator/core': 9.5.1
  '@stryker-mutator/typescript-checker': 9.5.1
  '@stryker-mutator/vitest-runner': 9.5.1
  '@simplewebauthn/server': 13.2.2
  '@sonar/scan': 4.3.4
  '@swc-node/register': 1.11.1
  '@swc/core': 1.15.11
  '@tailwindcss/vite': 4.1.18
  '@tanstack/react-table': 8.21.3
  '@tanstack/react-virtual': 3.13.18
  '@testing-library/react': 16.3.2
  '@types/k6': 1.6.0
  '@types/node': 25.2.3
  '@types/nodemailer': 7.0.10
  '@types/papaparse': 5.5.2
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@types/sax': 1.2.7
  '@use-gesture/react': 10.3.1
  '@vitejs/plugin-react': 5.1.4
  '@vitest/browser-playwright': 4.0.18
  '@vitest/coverage-v8': 4.0.18
  '@vitest/ui': 4.0.18
  '@xmldom/xmldom': 0.8.11
  arctic: 3.7.0
  babel-plugin-react-compiler: 1.0.0
  browserslist: 4.28.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  colorjs.io: 0.6.1
  date-fns: 4.1.0
  effect: 3.19.18
  exceljs: 4.4.0
  fake-indexeddb: 6.2.5
  fast-check: 4.5.3
  happy-dom: 20.6.1
  idb-keyval: 6.2.2
  immer: 11.1.4
  ioredis: 5.9.3
  ipaddr.js: 2.3.0
  jsdom: 28.1.0
  isomorphic-dompurify: 2.35.0
  jspdf: 4.1.0
  jszip: 3.10.1
  knip: 5.83.1
  lefthook: 2.1.1
  lightningcss: 1.31.1
  lucide-react: 0.569.0
  motion: 12.34.0
  nanoid: 5.1.6
  nodemailer: 8.0.1
  nuqs: 2.8.8
  nx: 22.5.1
  otplib: 13.3.0
  papaparse: 5.5.3
  react: 19.3.0-canary-f93b9fd4-20251217
  react-aria: 3.46.0
  react-aria-components: 1.15.1
  react-compiler-runtime: 1.0.0
  react-dom: 19.3.0-canary-f93b9fd4-20251217
  react-error-boundary: 6.1.1
  react-stately: 3.44.0
  rfc6902: 5.1.2
  rollup-plugin-visualizer: 6.0.5
  sax: 1.4.4
  sharp: 0.34.5
  sherif: 1.10.0
  tailwind-merge: 3.4.1
  tailwindcss: 4.1.18
  tailwindcss-react-aria-components: 2.0.1
  testcontainers: 11.11.0
  ts-essentials: 10.1.1
  ts-toolbelt: 9.6.0
  tslib: 2.8.1
  tsx: 4.21.0
  tw-animate-css: 1.4.0
  type-fest: 5.4.4
  typescript: 6.0.0-dev.20251125
  uuid: 13.0.0
  vaul: 1.1.2
  vite: 7.3.1
  vite-plugin-compression: 0.5.1
  vite-plugin-csp: 1.1.2
  vite-plugin-image-optimizer: 2.0.3
  vite-plugin-inspect: 11.3.3
  vite-plugin-pwa: 1.2.0
  vite-plugin-svgr: 4.5.0
  vite-plugin-webfont-dl: 3.12.0
  vite-tsconfig-paths: 6.1.1
  vitest: 4.0.18
  vitest-browser-react: 2.0.5
  yaml: 2.8.2
  zundo: 2.3.0
  zustand: 5.0.11
  zustand-computed: 2.1.1
  zustand-slices: 0.4.0

catalogMode: strict

cleanupUnusedCatalogs: false

engineStrict: true

fetchRetries: 3

fetchRetryFactor: 2

fetchRetryMaxtimeout: 60000

fetchRetryMintimeout: 10000

linkWorkspacePackages: deep

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@pulumi/command'
  - '@swc/core'
  - lefthook
  - sharp

preferWorkspacePackages: true

saveExact: true

strictSsl: true

verify-deps-before-run: warn
