packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.7
  '@effect/experimental': 0.57.4
  '@effect/platform': 0.93.3
  '@effect/platform-browser': 0.73.0
  '@effect/schema': 0.75.5
  '@nx/js': 22.2.0-canary.20251121-9a6c7ad
  '@nx/react': 22.2.0-canary.20251121-9a6c7ad
  '@nx/vite': 22.2.0-canary.20251121-9a6c7ad
  '@playwright/test': 1.56.1
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-separator': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@rollup/plugin-typescript': 12.3.0
  '@tailwindcss/vite': 4.1.17
  '@tanstack/react-query': 5.90.10
  '@tanstack/react-query-devtools': 5.91.0
  '@tanstack/react-query-persist-client': 5.90.12
  '@tanstack/react-table': 8.21.3
  '@tanstack/react-virtual': 3.13.12
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@types/uuid': 10.0.0
  '@vitejs/plugin-react': 5.1.1
  '@vitest/coverage-v8': 4.0.13
  '@vitest/ui': 4.0.13
  babel-plugin-react-compiler: 19.0.0-beta-9ee70a1-20241017
  browserslist: 4.28.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  date-fns: 4.1.0
  effect: 3.19.6
  happy-dom: 20.0.10
  immer: 11.0.0
  jspdf: 3.0.4
  jszip: 3.10.1
  lefthook: 2.0.4
  lightningcss: 1.30.2
  lucide-react: 0.554.0
  nx: 22.2.0-canary.20251121-9a6c7ad
  react: 19.3.0-canary-40b4a5bf-20251120
  react-aria: 3.44.0
  react-compiler-runtime: 19.0.0-beta-af1b7da-20250417
  react-dom: 19.3.0-canary-40b4a5bf-20251120
  react-stately: 3.42.0
  rollup-plugin-visualizer: 6.0.5
  sharp: 0.34.5
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  ts-pattern: 5.9.0
  tslib: 2.8.1
  tsx: 4.20.6
  typescript: 6.0.0-dev.20251121
  uuid: 10.0.0
  vite: 7.2.4
  vite-plugin-compression: 0.5.1
  vite-plugin-csp: 1.1.2
  vite-plugin-image-optimizer: 2.0.3
  vite-plugin-inspect: 11.3.3
  vite-plugin-pwa: 1.1.0
  vite-plugin-svgr: 4.5.0
  vite-plugin-webfont-dl: 3.11.1
  vite-tsconfig-paths: 5.1.4
  vitest: 4.0.13
  zod: 4.1.13
  zustand: 5.0.8
