packages:
  - apps/*
  - packages/*

catalog:
  '@anthropic-ai/sdk': 0.71.2
  '@anthropic-ai/tokenizer': 0.0.4
  '@axe-core/playwright': 4.10.0
  '@biomejs/biome': 2.3.10
  '@effect/experimental': 0.58.0
  '@effect/platform': 0.94.0
  '@effect/platform-browser': 0.74.0
  '@effect/platform-node': 0.78.0
  '@effect/sql': 0.49.0
  '@effect/sql-pg': 0.50.0
  '@effect/vitest': 0.27.0
  '@fast-check/vitest': 0.2.4
  '@floating-ui/react-dom': 2.1.6
  '@mermaid-js/layout-elk': 0.2.0
  '@mermaid-js/mermaid-cli': 11.12.0
  '@nx/js': 22.3.3
  '@nx/react': 22.3.3
  '@nx/vite': 22.3.3
  '@nx/vitest': 22.3.3
  '@octokit/rest': 22.0.1
  '@playwright/test': 1.57.0
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-separator': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@rollup/plugin-typescript': 12.3.0
  '@rottitime/react-hook-message-event': 1.0.10
  '@sonar/scan': 4.3.2
  '@stryker-mutator/core': 9.4.0
  '@stryker-mutator/vitest-runner': 9.4.0
  '@tailwindcss/vite': 4.1.18
  '@tanstack/react-query': 5.90.12
  '@tanstack/react-query-devtools': 5.91.1
  '@tanstack/react-query-persist-client': 5.90.14
  '@tanstack/react-table': 8.21.3
  '@tanstack/react-virtual': 3.13.13
  '@testing-library/react': 16.3.1
  '@types/node': 25.0.3
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@types/supertest': 6.0.2
  '@vitejs/plugin-react': 5.1.2
  '@vitest/browser-playwright': 4.0.16
  '@vitest/coverage-v8': 4.0.16
  '@vitest/ui': 4.0.16
  arctic: 3.7.0
  babel-plugin-react-compiler: 19.0.0-beta-ebf51a3-20250411
  browserslist: 4.28.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  date-fns: 4.1.0
  dompurify: 3.3.1
  effect: 3.19.13
  fake-indexeddb: 6.2.5
  fast-check: 4.5.1
  happy-dom: 20.0.11
  idb-keyval: 6.2.1
  immer: 11.1.0
  isomorphic-dompurify: 2.34.0
  jspdf: 3.0.4
  jszip: 3.10.1
  lefthook: 2.0.12
  lightningcss: 1.30.2
  lost-pixel: 3.27.0
  lucide-react: 0.562.0
  mermaid: 11.12.2
  msw: 2.8.0
  nuqs: 2.8.5
  nx: 22.3.3
  persist-and-sync: 1.2.3
  react: 19.3.0-canary-f93b9fd4-20251217
  react-aria: 3.45.0
  react-aria-components: 1.14.0
  react-compiler-runtime: 19.0.0-beta-ebf51a3-20250411
  react-dom: 19.3.0-canary-f93b9fd4-20251217
  react-error-boundary: 6.0.0
  react-stately: 3.43.0
  rollup-plugin-visualizer: 6.0.5
  sharp: 0.34.5
  snapshot-diff: 0.10.0
  supertest: 7.1.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tslib: 2.8.1
  tsx: 4.21.0
  typescript: 6.0.0-dev.20251125
  unplugin-auto-import: 20.3.0
  uuid: 13.0.0
  vite: 7.3.0
  vite-plugin-compression: 0.5.1
  vite-plugin-csp: 1.1.2
  vite-plugin-image-optimizer: 2.0.3
  vite-plugin-inspect: 11.3.3
  vite-plugin-pwa: 1.2.0
  vite-plugin-svgr: 4.5.0
  vite-plugin-webfont-dl: 3.11.1
  vite-tsconfig-paths: 6.0.3
  vitest: 4.0.16
  vitest-axe: 0.1.0
  vitest-browser-react: 2.0.2
  zundo: 2.3.0
  zustand: 5.0.9
  zustand-computed: 2.1.1
  zustand-slices: 0.4.0
  zustand-x: 6.2.1

dangerouslyAllowAllBuilds: true
