packages:
  - apps/*
  - packages/*

catalog:
  '@anthropic-ai/tokenizer': 0.0.4
  '@aws-sdk/client-s3': 3.750.0
  '@aws-sdk/s3-request-presigner': 3.750.0
  '@berenddeboer/nx-biome': 1.0.2
  '@biomejs/biome': 2.3.11
  '@effect-aws/client-s3': 1.10.7
  '@effect/ai': 0.33.2
  '@effect/ai-anthropic': 0.23.0
  '@effect/ai-google': 0.12.1
  '@effect/ai-openai': 0.37.2
  '@effect/experimental': 0.58.0
  '@effect/opentelemetry': 0.61.0
  '@effect/platform': 0.94.2
  '@effect/platform-browser': 0.74.0
  '@effect/platform-node': 0.104.0
  '@effect/sql': 0.49.0
  '@effect/sql-pg': 0.50.1
  '@effect/vitest': 0.27.0
  '@fast-check/vitest': 0.2.4
  '@floating-ui/react': 0.27.16
  '@floating-ui/react-dom': 2.1.6
  '@formkit/auto-animate': 0.9.0
  '@gltf-transform/core': 4.3.0
  '@internationalized/date': 3.10.1
  '@mermaid-js/mermaid-cli': 11.12.0
  '@nx/docker': 22.4.1
  '@nx/js': 22.4.1
  '@nx/playwright': 22.4.1
  '@nx/react': 22.4.1
  '@nx/vite': 22.4.1
  '@nx/vitest': 22.4.1
  '@octokit/rest': 22.0.1
  '@playwright/test': 1.58.0
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-separator': 1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-visually-hidden': 1.2.4
  '@react-aria/live-announcer': 3.4.4
  '@rollup/plugin-typescript': 12.3.0
  '@sonar/scan': 4.3.4
  '@stryker-mutator/core': 9.4.0
  '@stryker-mutator/vitest-runner': 9.4.0
  '@swc-node/register': 1.11.1
  '@swc/core': 1.15.10
  '@tailwindcss/vite': 4.1.18
  '@tanstack/react-table': 8.21.3
  '@tanstack/react-virtual': 3.13.18
  '@testing-library/react': 16.3.1
  '@types/node': 25.0.10
  '@types/papaparse': 5.5.2
  '@types/react': 19.2.9
  '@types/react-dom': 19.2.3
  '@types/sax': 1.2.7
  '@use-gesture/react': 10.3.1
  '@vitejs/plugin-react': 5.1.2
  '@vitest/browser-playwright': 4.0.18
  '@vitest/coverage-v8': 4.0.18
  '@vitest/ui': 4.0.18
  '@xmldom/xmldom': 0.8.11
  arctic: 3.7.0
  babel-plugin-react-compiler: 1.0.0
  browserslist: 4.28.1
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  cockatiel: 3.2.1
  colorjs.io: 0.6.0
  date-fns: 4.1.0
  effect: 3.19.15
  exceljs: 4.4.0
  fake-indexeddb: 6.2.5
  fast-check: 4.5.3
  happy-dom: 20.3.7
  idb-keyval: 6.2.2
  immer: 11.1.3
  ioredis: 5.9.1
  ipaddr.js: 2.2.0
  isomorphic-dompurify: 2.35.0
  jspdf: 4.0.0
  jszip: 3.10.1
  knip: 5.82.1
  lefthook: 2.0.15
  lightningcss: 1.31.1
  lucide-react: 0.563.0
  motion: 12.26.1
  msw: 2.12.7
  nanoid: 5.1.6
  nuqs: 2.8.6
  nx: 22.4.1
  otplib: 13.1.0
  papaparse: 5.5.2
  react: 19.3.0-canary-f93b9fd4-20251217
  react-aria: 3.45.0
  react-aria-components: 1.14.0
  react-compiler-runtime: 1.0.0
  react-dom: 19.3.0-canary-f93b9fd4-20251217
  react-error-boundary: 6.0.3
  react-stately: 3.43.0
  rfc6902: 5.1.1
  rollup-plugin-visualizer: 6.0.5
  sax: 1.4.4
  sharp: 0.34.5
  sherif: 1.10.0
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tailwindcss-react-aria-components: 2.0.1
  ts-essentials: 10.1.1
  ts-toolbelt: 9.6.0
  tslib: 2.8.1
  tsx: 4.21.0
  tw-animate-css: 1.4.0
  type-fest: 5.4.0
  typescript: 6.0.0-dev.20251125
  unplugin-auto-import: 20.3.0
  uuid: 11.1.0
  vaul: 1.1.2
  vite: 7.3.1
  vite-plugin-compression: 0.5.1
  vite-plugin-csp: 1.1.2
  vite-plugin-image-optimizer: 2.0.3
  vite-plugin-inspect: 11.3.3
  vite-plugin-pwa: 1.2.0
  vite-plugin-svgr: 4.5.0
  vite-plugin-webfont-dl: 3.11.1
  vite-tsconfig-paths: 6.0.5
  vitest: 4.0.18
  vitest-browser-react: 2.0.2
  yaml: 2.7.1
  zundo: 2.3.0
  zustand: 5.0.10
  zustand-computed: 2.1.1
  zustand-slices: 0.4.0

catalogMode: strict

cleanupUnusedCatalogs: true

dangerouslyAllowAllBuilds: true

dedupeInjectedDeps: true

dedupePeerDependents: true

engineStrict: true

fetchRetries: 3

fetchRetryFactor: 2

fetchRetryMaxtimeout: 60000

fetchRetryMintimeout: 10000

inject-workspace-packages: true

linkWorkspacePackages: deep

preferWorkspacePackages: true

saveExact: true

strictSsl: true

verify-deps-before-run: install
