name: Claude Code Setup
description: Install and cache Claude Code CLI

outputs:
    executable:
        description: Path to Claude Code executable
        value: ${{ steps.path.outputs.executable }}

runs:
    using: composite
    steps:
        - name: Cache Claude Code CLI
          id: cache
          uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
          with:
              path: ~/.claude
              key: claude-code-${{ runner.os }}-v1

        - name: Install Claude Code CLI
          if: steps.cache.outputs.cache-hit != 'true'
          shell: bash
          run: curl -fsSL https://claude.ai/install.sh | bash

        - name: Set executable path
          id: path
          shell: bash
          run: echo "executable=$HOME/.claude/local/bin/claude" >> "$GITHUB_OUTPUT"
