# --- MONITORING LGTM KYVERNO EXCEPTION ----------------------------------------
# Exempt LGTM stack components from strict security policies
# Grafana, Mimir, Loki, Tempo, Alloy require specific relaxed constraints
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: lgtm-stack-exception
  namespace: kyverno
spec:
  exceptions:
    - policyName: require-run-as-nonroot
      ruleNames:
        - run-as-non-root
        - autogen-run-as-non-root
    - policyName: disallow-privilege-escalation
      ruleNames:
        - privilege-escalation
        - autogen-privilege-escalation
    - policyName: require-ro-rootfs
      ruleNames:
        - validate-readOnlyRootFilesystem
        - autogen-validate-readOnlyRootFilesystem
    - policyName: require-requests-limits
      ruleNames:
        - validate-resources
        - autogen-validate-resources
    - policyName: restrict-image-registries
      ruleNames:
        - validate-registries
        - autogen-validate-registries
  match:
    any:
      - resources:
          kinds:
            - Pod
            - Deployment
            - StatefulSet
            - DaemonSet
            - ReplicaSet
          namespaces:
            - monitoring
          names:
            - lgtm-*
            - grafana-*
            - mimir-*
            - loki-*
            - tempo-*
            - alloy-*
