# --- CERT-MANAGER PODMONITOR --------------------------------------------------
# Prometheus scraping for cert-manager TLS automation
# Metrics: certmanager_certificate_*, certmanager_controller_*
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: tls
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
---
# --- CERT-MANAGER WEBHOOK PODMONITOR ------------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cert-manager-webhook
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: webhook
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
---
# --- CERT-MANAGER CAINJECTOR PODMONITOR ---------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cert-manager-cainjector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cainjector
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: cainjector
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
