# --- ARGOCD PODMONITOR --------------------------------------------------------
# Scrape ArgoCD metrics for Grafana dashboards
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  namespaceSelector:
    matchNames:
      - argocd
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
# --- ARGOCD APPLICATION CONTROLLER PODMONITOR ---------------------------------
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-application-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  namespaceSelector:
    matchNames:
      - argocd
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
# --- ARGOCD REPO SERVER PODMONITOR --------------------------------------------
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-repo-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  namespaceSelector:
    matchNames:
      - argocd
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
