# --- LONGHORN PODMONITOR ------------------------------------------------------
# Prometheus scraping for Longhorn storage manager
# Metrics: longhorn_volume_*, longhorn_node_*, longhorn_disk_*
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: longhorn-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storage
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - longhorn-system
  selector:
    matchLabels:
      app: longhorn-manager
  podMetricsEndpoints:
    - port: manager
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
