# --- REDIS PASSWORD SECRET TEMPLATE -------------------------------------------
# Redis authentication password for Sentinel HA cluster
#
# [IMPORTANT] Use ExternalSecrets or SealedSecrets for production
# This placeholder allows local development; replace before deployment
#
# Production options:
#   1. SealedSecrets: kubeseal --cert <cert> < secret.yaml > sealed-secret.yaml
#   2. ExternalSecrets: Create ExternalSecret referencing external store
#   3. kubectl create secret: kubectl create secret generic redis-password \
#        --from-literal=redis-password=<password> -n redis-system
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: redis-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
  annotations:
    parametric-portal.com/secret-source: "placeholder"
type: Opaque
stringData:
  redis-password: "REPLACE_WITH_SEALED_SECRET"
