name: Node Environment
description: Node.js + pnpm setup with caching, Nx monorepo support, and distributed task execution
inputs:
    node-version:
        description: Node.js version (ignored if node-version-file is set)
        default: '25.2.1'
    node-version-file:
        description: File containing Node.js version (e.g., package.json)
        required: false
    pnpm-version:
        description: pnpm version
        default: '10.24.0'
    install:
        description: Run pnpm install
        default: 'true'
    frozen-lockfile:
        description: Use --frozen-lockfile flag
        default: 'true'
    nx:
        description: Enable Nx caching and affected setup
        default: 'false'
    nx-cloud-token:
        description: Nx Cloud access token (enables remote cache)
        required: false
    nx-main-branch:
        description: Main branch for affected comparison
        default: 'main'
    nx-distribute:
        description: Enable Nx Agents for distributed task execution
        default: 'false'
    nx-distribute-config:
        description: Path to dynamic agent distribution config (e.g., .nx/workflows/distribution-config.yaml)
        default: ''
    nx-agents:
        description: Number of Nx Agents for distribution (fallback if no config specified)
        default: '3'
    nx-stop-on-success:
        description: Stop agents when first non-dependent run group succeeds
        default: 'true'
    nx-auto-fix:
        description: Enable Nx Cloud auto-apply-fixes feature
        default: 'false'
    nx-fix-tasks:
        description: Glob patterns for tasks eligible for auto-fix (e.g., *check*,*lint* or * for all)
        default: '*'

outputs:
    nx-base:
        description: Base SHA for Nx affected commands
        value: ${{ steps.shas.outputs.base }}
    nx-head:
        description: Head SHA for Nx affected commands
        value: ${{ steps.shas.outputs.head }}

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
          with:
              version: ${{ inputs.pnpm-version }}
        - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
          with:
              node-version: ${{ inputs.node-version-file && '' || inputs.node-version }}
              node-version-file: ${{ inputs.node-version-file }}
              cache: pnpm

        # Nx Cloud remote cache - set token early for nx-cloud CLI
        - name: Configure Nx Cloud
          if: inputs.nx == 'true' && inputs.nx-cloud-token != ''
          shell: bash
          run: echo "NX_CLOUD_ACCESS_TOKEN=${{ inputs.nx-cloud-token }}" >> $GITHUB_ENV

        # Start distributed CI run BEFORE dependencies (TTG optimization)
        # See: https://nx.dev/docs/guides/nx-cloud/optimize-your-ttg
        - name: Start Nx Agents
          if: inputs.nx == 'true' && inputs.nx-distribute == 'true' && inputs.nx-cloud-token != ''
          shell: bash
          run: |
              # Use dynamic config file if provided, otherwise use fixed agent count and machine type
              DISTRIBUTE_ON="${{ inputs.nx-distribute-config != '' && inputs.nx-distribute-config || format('{0} linux-medium-js', env.AGENTS) }}"
              npx nx-cloud start-ci-run \
                --distribute-on="$DISTRIBUTE_ON" \
                --stop-agents-after=typecheck,build,test \
                ${{ inputs.nx-stop-on-success == 'true' && '--stop-agents-on-failure' || '' }} \
                ${{ inputs.nx-auto-fix == 'true' && format('--auto-apply-fixes={0}', inputs.nx-fix-tasks) || '' }} \
                ${{ inputs.nx-auto-fix == 'true' && format('--fix-tasks={0}', inputs.nx-fix-tasks) || '' }}
          env:
              AGENTS: ${{ inputs.nx-agents }}

        # Install dependencies after Nx Agents start
        - if: inputs.install == 'true'
          shell: bash
          run: pnpm install ${{ inputs.frozen-lockfile == 'true' && '--frozen-lockfile' || '' }}

        # Nx local cache
        - name: Restore Nx cache
          if: inputs.nx == 'true'
          uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
          with:
              path: .nx/cache
              key: ${{ runner.os }}-nx-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
              restore-keys: |
                  ${{ runner.os }}-nx-${{ hashFiles('pnpm-lock.yaml') }}-
                  ${{ runner.os }}-nx-

        # Set base/head SHAs for affected commands
        - name: Set affected SHAs
          id: shas
          if: inputs.nx == 'true'
          uses: nrwl/nx-set-shas@3e9ad7370203c1e93d109be57f3b72eb0eb511b1 # v4.4.0
          with:
              main-branch-name: ${{ inputs.nx-main-branch }}
