name: Node Environment
description: Node.js + pnpm setup from package.json
inputs:
    install:
        description: Run pnpm install
        default: 'true'
    frozen-lockfile:
        description: Use --frozen-lockfile flag
        default: 'true'

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

        - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.3.0
          with:
              node-version-file: package.json
              cache: ${{ inputs.install == 'true' && 'pnpm' || '' }}

        - name: Install dependencies
          if: inputs.install == 'true'
          shell: bash
          run: pnpm install ${{ inputs.frozen-lockfile == 'true' && '--frozen-lockfile' || '' }}
