name: Node Environment
description: Node.js + pnpm setup with caching
inputs:
    node-version:
        description: Node.js version (ignored if node-version-file is set)
        default: '25.2.1'
    node-version-file:
        description: File containing Node.js version (e.g., package.json)
        required: false
    pnpm-version:
        description: pnpm version
        default: '10.23.0'
    install:
        description: Run pnpm install
        default: 'true'
    frozen-lockfile:
        description: Use --frozen-lockfile flag
        default: 'true'
runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@c5ba7f7862a0f64c1b1a05fbac13e0b8e86ba08c # v4
          with:
              version: ${{ inputs.pnpm-version }}
        - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
          with:
              node-version: ${{ inputs.node-version-file && '' || inputs.node-version }}
              node-version-file: ${{ inputs.node-version-file }}
              cache: pnpm
        - if: inputs.install == 'true'
          shell: bash
          run: pnpm install ${{ inputs.frozen-lockfile == 'true' && '--frozen-lockfile' || '' }}
