name: Node Environment
description: Node.js + pnpm setup with caching, Nx monorepo support, and distributed task execution
inputs:
    node-version:
        description: Node.js version (ignored if node-version-file is set)
        default: '25.2.1'
    node-version-file:
        description: File containing Node.js version (e.g., package.json)
        required: false
    pnpm-version:
        description: pnpm version
        default: '10.23.0'
    install:
        description: Run pnpm install
        default: 'true'
    frozen-lockfile:
        description: Use --frozen-lockfile flag
        default: 'true'
    nx:
        description: Enable Nx caching and affected setup
        default: 'false'
    nx-cloud-token:
        description: Nx Cloud access token (enables remote cache)
        required: false
    nx-main-branch:
        description: Main branch for affected comparison
        default: 'main'
    nx-distribute:
        description: Enable Nx Agents for distributed task execution
        default: 'false'
    nx-agents:
        description: Number of Nx Agents for distribution (1-10)
        default: '3'
    nx-stop-on-success:
        description: Stop agents when first non-dependent run group succeeds
        default: 'true'

outputs:
    nx-base:
        description: Base SHA for Nx affected commands
        value: ${{ steps.shas.outputs.base }}
    nx-head:
        description: Head SHA for Nx affected commands
        value: ${{ steps.shas.outputs.head }}

runs:
    using: composite
    steps:
        - uses: pnpm/action-setup@c5ba7f7862a0f64c1b1a05fbac13e0b8e86ba08c # v4
          with:
              version: ${{ inputs.pnpm-version }}
        - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
          with:
              node-version: ${{ inputs.node-version-file && '' || inputs.node-version }}
              node-version-file: ${{ inputs.node-version-file }}
              cache: pnpm
        - if: inputs.install == 'true'
          shell: bash
          run: pnpm install ${{ inputs.frozen-lockfile == 'true' && '--frozen-lockfile' || '' }}

        # Nx local cache
        - name: Restore Nx cache
          if: inputs.nx == 'true'
          uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
          with:
              path: .nx/cache
              key: ${{ runner.os }}-nx-${{ hashFiles('pnpm-lock.yaml') }}-${{ github.sha }}
              restore-keys: |
                  ${{ runner.os }}-nx-${{ hashFiles('pnpm-lock.yaml') }}-
                  ${{ runner.os }}-nx-

        # Nx Cloud remote cache
        - name: Configure Nx Cloud
          if: inputs.nx == 'true' && inputs.nx-cloud-token != ''
          shell: bash
          run: echo "NX_CLOUD_ACCESS_TOKEN=${{ inputs.nx-cloud-token }}" >> $GITHUB_ENV

        # Set base/head SHAs for affected commands
        - name: Set affected SHAs
          id: shas
          if: inputs.nx == 'true'
          uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4.3.0
          with:
              main-branch-name: ${{ inputs.nx-main-branch }}

        # Start distributed CI run with Nx Agents
        - name: Start Nx Agents
          if: inputs.nx == 'true' && inputs.nx-distribute == 'true' && inputs.nx-cloud-token != ''
          shell: bash
          run: |
              npx nx-cloud start-ci-run \
                --distribute-on="$AGENTS linux-medium-jvm" \
                --stop-agents-after=build \
                ${{ inputs.nx-stop-on-success == 'true' && '--stop-agents-on-failure' || '' }}
          env:
              AGENTS: ${{ inputs.nx-agents }}
