name: '[ACTION_NAME]'
description: '[ACTION_DESCRIPTION]'
author: '[AUTHOR_NAME]'

inputs:
  [input-name]:
    description: '[INPUT_DESCRIPTION]'
    required: [true/false]
    default: '[DEFAULT_VALUE]'

outputs:
  [output-name]:
    description: '[OUTPUT_DESCRIPTION]'
    value: ${{ steps.[step-id].outputs.[output-name] }}

branding:
  icon: '[ICON_NAME]'
  color: '[COLOR]'  # white|yellow|blue|green|orange|red|purple|gray-dark

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.[input-name] }}" ]; then
          echo "::error::Input [input-name] is required"; exit 1
        fi

    - name: [SETUP_STEP_NAME]
      uses: [SETUP_ACTION]@[SHA] # [VERSION]
      with: { [SETUP_INPUT]: '${{ inputs.[input-name] }}' }

    - name: [MAIN_STEP_NAME]
      id: [step-id]
      shell: bash
      env: { INPUT_VALUE: '${{ inputs.[input-name] }}' }
      run: |
        [MAIN_COMMAND]
        echo "[output-name]=[OUTPUT_VALUE]" >> $GITHUB_OUTPUT

    - name: Cleanup
      if: always()
      shell: bash
      run: echo "Cleanup completed" # Add cleanup logic
