/// <reference types="vite/client" />
/**
 * Test harness Vite config: Dracula theme + Button ComponentSpec.
 * Validates theme generation + component wiring pipeline.
 */
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { devtoolsPlugin } from '@parametric-portal/devtools/vite-plugin';
import { defineTheme, type ThemeConfig } from '@parametric-portal/theme/theme';
import { Effect } from 'effect';
import { defineConfig } from 'vite';
import { createConfig } from '../../vite.factory.ts';

// --- [CONSTANTS] -------------------------------------------------------------

const APP_ROOT = dirname(fileURLToPath(import.meta.url));
const B = Object.freeze({
    app: { name: 'TestHarness', port: 3002 },
    theme: {
        animation: { enterScale: 0.95, exitScale: 0.95 },
        colors: {
            // Dracula palette → OKLCH
            accent: { c: 0.22, h: 340, l: 0.72 }, // Pink #ff79c6
            danger: { c: 0.25, h: 25, l: 0.65 }, // Red #ff5555
            primary: { c: 0.18, h: 290, l: 0.72 }, // Purple #bd93f9
            secondary: { c: 0.12, h: 195, l: 0.85 }, // Cyan #8be9fd
            success: { c: 0.25, h: 145, l: 0.85 }, // Green #50fa7b
            surface: { c: 0.02, h: 260, l: 0.22 }, // Background #282a36
            text: { c: 0.01, h: 90, l: 0.97 }, // Foreground #f8f8f2
            warning: { c: 0.15, h: 55, l: 0.82 }, // Orange #ffb86c
        },
        components: [
            {
                asyncStyles: {
                    failure: { 'icon-animation': 'shake 0.3s ease-in-out' },
                    idle: { 'icon-animation': 'none' },
                    loading: { 'icon-animation': 'spin 0.8s ease-in-out infinite' },
                    success: { 'icon-animation': 'none' },
                },
                base: {
                    'disabled-opacity': '0.5',
                    'font-weight': '500',
                    'pressed-scale': '0.98',
                    radius: '0.5rem',
                    shadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorSlots: {
                    bg: '500',
                    'border-color': '500',
                    fg: 'text-on',
                    'hover-bg': 'hovered',
                    'pressed-bg': 'pressed',
                },
                longpress: {
                    animation: 'pulse 1s ease-in-out infinite',
                    background:
                        'conic-gradient(from 0deg, var(--focus-ring-color) calc(var(--button-longpress-progress) * 360deg), transparent 0deg)',
                    'border-radius': 'inherit',
                    content: "''",
                    inset: '-4px',
                    opacity: '0.5',
                    'pointer-events': 'none',
                    position: 'absolute',
                },
                name: 'button',
                sizes: {
                    lg: {
                        'font-size': '1rem',
                        gap: '0.625rem',
                        height: '3rem',
                        'icon-size': '1.25rem',
                        px: '1.25rem',
                        width: 'auto',
                    },
                    md: {
                        'font-size': '0.875rem',
                        gap: '0.5rem',
                        height: '2.5rem',
                        'icon-size': '1rem',
                        px: '1rem',
                        width: 'auto',
                    },
                    sm: {
                        'font-size': '0.75rem',
                        gap: '0.375rem',
                        height: '2rem',
                        'icon-size': '0.875rem',
                        px: '0.75rem',
                        width: 'auto',
                    },
                },
                variants: {
                    ghost: { bg: 'transparent', 'border-color': 'transparent', 'hover-bg': '100', shadow: 'none' },
                    outline: { bg: 'transparent', 'border-width': '1px', shadow: 'none' },
                    solid: { 'border-color': 'transparent' },
                },
            },
            {
                base: {
                    'active-border': 'var(--color-primary-400)',
                    bg: 'var(--color-surface-600)',
                    'border-style': 'dashed',
                    'border-width': '2px',
                    'disabled-opacity': '0.5',
                    'error-border': 'var(--color-danger-500)',
                    height: '12rem',
                    'idle-border': 'var(--color-text-800)',
                    radius: '0.75rem',
                    'transition-duration': '150ms',
                    width: '100%',
                },
                colorSlots: {},
                name: 'file-upload',
                sizes: {},
            },
            {
                base: {
                    bg: 'var(--color-surface-700)',
                    height: '8rem',
                    'icon-color': 'var(--color-text-600)',
                    'icon-size': '2rem',
                    'meta-bg': 'oklch(0 0 0 / 0.5)',
                    'meta-fg': 'var(--color-text-50)',
                    'meta-font-size': '0.75rem',
                    'meta-padding': '0.5rem',
                    radius: '0.5rem',
                    width: '8rem',
                },
                colorSlots: {},
                name: 'file-preview',
                sizes: {},
            },
            {
                base: {
                    'disabled-opacity': '0.5',
                    'label-color': 'var(--color-text-500)',
                    'selected-bg': 'var(--color-primary-500)',
                    'thumb-bg': 'var(--color-text-50)',
                    'thumb-shadow': '0 1px 3px rgb(0 0 0 / 0.2)',
                    'track-bg': 'var(--color-surface-600)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorSlots: { 'selected-bg': '500' },
                name: 'switch',
                sizes: {
                    lg: {
                        gap: '0.625rem',
                        'label-size': '1rem',
                        'thumb-offset': '0.1875rem',
                        'thumb-size': '1.5rem',
                        'track-height': '1.75rem',
                        'track-radius': '0.875rem',
                        'track-width': '3.25rem',
                    },
                    md: {
                        gap: '0.5rem',
                        'label-size': '0.875rem',
                        'thumb-offset': '0.125rem',
                        'thumb-size': '1.25rem',
                        'track-height': '1.5rem',
                        'track-radius': '0.75rem',
                        'track-width': '2.75rem',
                    },
                    sm: {
                        gap: '0.375rem',
                        'label-size': '0.75rem',
                        'thumb-offset': '0.0625rem',
                        'thumb-size': '1rem',
                        'track-height': '1.25rem',
                        'track-radius': '0.625rem',
                        'track-width': '2.25rem',
                    },
                },
                variants: {
                    default: {},
                    outline: { 'thumb-bg': 'var(--color-text-600)', 'track-bg': 'transparent' },
                },
            },
            {
                base: {
                    'border-color': 'var(--color-text-700)',
                    'border-width': '2px',
                    'box-bg': 'var(--color-surface-600)',
                    'box-radius': '0.25rem',
                    'disabled-opacity': '0.5',
                    'icon-color': 'var(--color-text-50)',
                    'invalid-border': 'var(--color-danger-500)',
                    'label-color': 'var(--color-text-500)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorInherit: 'checkbox-group',
                colorSlots: { 'selected-bg': '500', 'selected-border': '500' },
                name: 'checkbox',
                sizes: {
                    lg: {
                        'box-size': '1.5rem',
                        gap: '0.625rem',
                        'group-gap': '1rem',
                        'icon-size': '1rem',
                        'label-size': '1rem',
                    },
                    md: {
                        'box-size': '1.25rem',
                        gap: '0.5rem',
                        'group-gap': '0.75rem',
                        'icon-size': '0.875rem',
                        'label-size': '0.875rem',
                    },
                    sm: {
                        'box-size': '1rem',
                        gap: '0.375rem',
                        'group-gap': '0.5rem',
                        'icon-size': '0.75rem',
                        'label-size': '0.75rem',
                    },
                },
            },
            {
                base: {},
                colorSlots: {},
                name: 'checkbox-group',
                sizes: {
                    lg: { gap: '1rem' },
                    md: { gap: '0.75rem' },
                    sm: { gap: '0.5rem' },
                },
            },
            {
                base: {
                    'description-color': 'var(--color-text-600)',
                    'error-color': 'var(--color-danger-400)',
                    'label-color': 'var(--color-text-400)',
                    'label-weight': '500',
                    'segmented-bg': 'var(--color-surface-700)',
                    'segmented-radius': '0.5rem',
                },
                colorSlots: {},
                name: 'radio-group',
                sizes: {
                    lg: {
                        'description-size': '0.875rem',
                        'error-size': '0.875rem',
                        gap: '1rem',
                        'label-size': '1rem',
                        'segmented-gap': '0.1875rem',
                        'segmented-padding': '0.375rem',
                        'wrapper-gap': '0.625rem',
                    },
                    md: {
                        'description-size': '0.75rem',
                        'error-size': '0.75rem',
                        gap: '0.75rem',
                        'label-size': '0.875rem',
                        'segmented-gap': '0.125rem',
                        'segmented-padding': '0.25rem',
                        'wrapper-gap': '0.5rem',
                    },
                    sm: {
                        'description-size': '0.625rem',
                        'error-size': '0.625rem',
                        gap: '0.5rem',
                        'label-size': '0.75rem',
                        'segmented-gap': '0.0625rem',
                        'segmented-padding': '0.125rem',
                        'wrapper-gap': '0.375rem',
                    },
                },
            },
            {
                base: {
                    'border-color': 'var(--color-text-700)',
                    'border-width': '2px',
                    'card-bg': 'var(--color-surface-700)',
                    'card-border-color': 'var(--color-text-700)',
                    'card-border-width': '1px',
                    'card-hover-bg': 'var(--color-surface-600)',
                    'card-hover-border': 'var(--color-text-600)',
                    'card-radius': '0.5rem',
                    'circle-bg': 'var(--color-surface-600)',
                    'disabled-opacity': '0.5',
                    'icon-color': 'var(--color-text-50)',
                    'indicator-color': 'var(--color-text-50)',
                    'indicator-scale': '0',
                    'indicator-scale-selected': '1',
                    'invalid-border': 'var(--color-danger-500)',
                    'label-color': 'var(--color-text-500)',
                    'longpress-progress': '0',
                    'segmented-fg': 'var(--color-text-500)',
                    'segmented-font-weight': '500',
                    'segmented-hover-bg': 'var(--color-surface-600)',
                    'segmented-radius': '0.375rem',
                    'segmented-selected-shadow': '0 1px 2px rgb(0 0 0 / 0.1)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorInherit: 'radio-group',
                colorSlots: {
                    'card-selected-bg': '100',
                    'card-selected-border': '500',
                    'indicator-color': '500',
                    'segmented-selected-bg': '500',
                    'segmented-selected-fg': 'text-on',
                    'selected-bg': '500',
                    'selected-border': '500',
                },
                longpress: {
                    animation: 'pulse 1s ease-in-out infinite',
                    background:
                        'conic-gradient(from 0deg, var(--focus-ring-color) calc(var(--radio-longpress-progress) * 360deg), transparent 0deg)',
                    'border-radius': '50%',
                    content: "''",
                    inset: '-4px',
                    opacity: '0.5',
                    'pointer-events': 'none',
                    position: 'absolute',
                },
                name: 'radio',
                sizes: {
                    lg: {
                        'card-gap': '1rem',
                        'card-padding': '1.25rem',
                        'circle-size': '1.5rem',
                        gap: '0.625rem',
                        'icon-size': '0.625rem',
                        'indicator-size': '0.625rem',
                        'label-size': '1rem',
                        'segmented-font-size': '1rem',
                        'segmented-px': '1.25rem',
                        'segmented-py': '0.625rem',
                    },
                    md: {
                        'card-gap': '0.75rem',
                        'card-padding': '1rem',
                        'circle-size': '1.25rem',
                        gap: '0.5rem',
                        'icon-size': '0.5rem',
                        'indicator-size': '0.5rem',
                        'label-size': '0.875rem',
                        'segmented-font-size': '0.875rem',
                        'segmented-px': '1rem',
                        'segmented-py': '0.5rem',
                    },
                    sm: {
                        'card-gap': '0.5rem',
                        'card-padding': '0.75rem',
                        'circle-size': '1rem',
                        gap: '0.375rem',
                        'icon-size': '0.375rem',
                        'indicator-size': '0.375rem',
                        'label-size': '0.75rem',
                        'segmented-font-size': '0.75rem',
                        'segmented-px': '0.75rem',
                        'segmented-py': '0.375rem',
                    },
                },
            },
            {
                base: {
                    bg: 'var(--color-surface-600)',
                    'border-color': 'var(--color-text-800)',
                    'border-width': '1px',
                    'disabled-opacity': '0.5',
                    fg: 'var(--color-text-500)',
                    'font-weight': '500',
                    'icon-color': 'var(--color-text-600)',
                    'invalid-border': 'var(--color-danger-500)',
                    'item-badge-bg': 'var(--color-primary-500)',
                    'item-badge-fg': 'var(--color-text-50)',
                    'item-badge-max': '99',
                    'item-description-fg': 'var(--color-text-600)',
                    'item-destructive-fg': 'var(--color-danger-500)',
                    'item-destructive-hover-bg': 'var(--color-danger-100)',
                    'item-disabled-opacity': '0.5',
                    'item-fg': 'var(--color-text-500)',
                    'item-radius': '0.375rem',
                    'listbox-bg': 'var(--color-surface-700)',
                    'listbox-border-color': 'var(--color-surface-600)',
                    'listbox-border-width': '1px',
                    'listbox-max-height': '16rem',
                    'listbox-padding': '0.25rem',
                    'listbox-radius': '0.5rem',
                    'listbox-shadow': '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'placeholder-color': 'var(--color-text-700)',
                    'popover-animation-offset': '0.5rem',
                    'popover-animation-scale': '0.95',
                    'popover-offset': '4',
                    radius: '0.5rem',
                    'section-header-fg': 'var(--color-text-700)',
                    'section-header-font-weight': '600',
                    'separator-color': 'var(--color-surface-600)',
                    'separator-height': '1px',
                    'separator-my': '0.25rem',
                    shadow: '0 1px 2px rgb(0 0 0 / 0.05)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                    width: 'auto',
                },
                colorSlots: {
                    'hover-bg': 'hovered',
                    'hover-border': 'hovered',
                    'item-focused-bg': '100',
                    'item-hover-bg': '100',
                    'item-pressed-bg': '200',
                    'item-selected-bg': '500',
                    'item-selected-fg': 'text-on',
                    'pressed-bg': 'pressed',
                },
                name: 'select',
                sizes: {
                    lg: {
                        'font-size': '1rem',
                        gap: '0.625rem',
                        height: '3rem',
                        'icon-size': '1.25rem',
                        'item-badge-font-size': '0.75rem',
                        'item-badge-min-width': '1.5rem',
                        'item-badge-padding-x': '0.5rem',
                        'item-badge-radius': '0.75rem',
                        'item-description-font-size': '0.875rem',
                        'item-font-size': '1rem',
                        'item-gap': '0.625rem',
                        'item-height': '2.5rem',
                        'item-icon-size': '1.25rem',
                        'item-px': '1rem',
                        px: '1rem',
                        'section-header-font-size': '0.875rem',
                        'section-header-px': '1rem',
                        'section-header-py': '0.625rem',
                    },
                    md: {
                        'font-size': '0.875rem',
                        gap: '0.5rem',
                        height: '2.5rem',
                        'icon-size': '1rem',
                        'item-badge-font-size': '0.625rem',
                        'item-badge-min-width': '1.25rem',
                        'item-badge-padding-x': '0.375rem',
                        'item-badge-radius': '0.625rem',
                        'item-description-font-size': '0.75rem',
                        'item-font-size': '0.875rem',
                        'item-gap': '0.5rem',
                        'item-height': '2.25rem',
                        'item-icon-size': '1rem',
                        'item-px': '0.75rem',
                        px: '0.75rem',
                        'section-header-font-size': '0.75rem',
                        'section-header-px': '0.75rem',
                        'section-header-py': '0.5rem',
                    },
                    sm: {
                        'font-size': '0.75rem',
                        gap: '0.375rem',
                        height: '2rem',
                        'icon-size': '0.875rem',
                        'item-badge-font-size': '0.5rem',
                        'item-badge-min-width': '1rem',
                        'item-badge-padding-x': '0.25rem',
                        'item-badge-radius': '0.5rem',
                        'item-description-font-size': '0.625rem',
                        'item-font-size': '0.75rem',
                        'item-gap': '0.375rem',
                        'item-height': '1.75rem',
                        'item-icon-size': '0.875rem',
                        'item-px': '0.5rem',
                        px: '0.5rem',
                        'section-header-font-size': '0.625rem',
                        'section-header-px': '0.5rem',
                        'section-header-py': '0.375rem',
                    },
                },
            },
            // --- Field Component (unified text/search/number) ---
            {
                asyncStyles: {
                    failure: { 'icon-animation': 'shake 0.3s ease-in-out' },
                    idle: { 'icon-animation': 'none' },
                    loading: { 'icon-animation': 'spin 0.8s ease-in-out infinite' },
                    success: { 'icon-animation': 'none' },
                },
                base: {
                    bg: 'var(--color-surface-600)',
                    'border-color': 'var(--color-text-800)',
                    'border-width': '1px',
                    'clear-color': 'var(--color-text-600)',
                    'clear-radius': '0.25rem',
                    'description-color': 'var(--color-text-600)',
                    'disabled-opacity': '0.5',
                    'error-color': 'var(--color-danger-400)',
                    'icon-color': 'var(--color-text-600)',
                    'input-color': 'var(--color-text-500)',
                    'invalid-border': 'var(--color-danger-500)',
                    'label-color': 'var(--color-text-500)',
                    'label-weight': '500',
                    'placeholder-color': 'var(--color-text-700)',
                    radius: '0.5rem',
                    'stepper-color': 'var(--color-text-600)',
                    'stepper-disabled-opacity': '0.5',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorSlots: {
                    'clear-hover-bg': '100',
                    'clear-pressed-bg': '200',
                    'focus-border': '500',
                    'hover-bg': '50',
                    'hover-border': '400',
                    'stepper-hover-bg': '100',
                    'stepper-pressed-bg': '200',
                },
                name: 'field',
                sizes: {
                    lg: {
                        'clear-icon-size': '1rem',
                        'clear-size': '1.75rem',
                        'description-size': '0.875rem',
                        'error-size': '0.875rem',
                        'font-size': '1rem',
                        gap: '0.625rem',
                        height: '3rem',
                        'icon-size': '1.25rem',
                        'input-width': '4rem',
                        'label-size': '1rem',
                        px: '1rem',
                        py: '0.75rem',
                        'stepper-icon-size': '1rem',
                        'stepper-size': '2.5rem',
                        'textarea-min-height': '6rem',
                        'wrapper-gap': '0.5rem',
                    },
                    md: {
                        'clear-icon-size': '0.875rem',
                        'clear-size': '1.5rem',
                        'description-size': '0.75rem',
                        'error-size': '0.75rem',
                        'font-size': '0.875rem',
                        gap: '0.5rem',
                        height: '2.5rem',
                        'icon-size': '1rem',
                        'input-width': '3.5rem',
                        'label-size': '0.875rem',
                        px: '0.75rem',
                        py: '0.5rem',
                        'stepper-icon-size': '0.875rem',
                        'stepper-size': '2rem',
                        'textarea-min-height': '5rem',
                        'wrapper-gap': '0.375rem',
                    },
                    sm: {
                        'clear-icon-size': '0.75rem',
                        'clear-size': '1.25rem',
                        'description-size': '0.625rem',
                        'error-size': '0.625rem',
                        'font-size': '0.75rem',
                        gap: '0.375rem',
                        height: '2rem',
                        'icon-size': '0.875rem',
                        'input-width': '3rem',
                        'label-size': '0.75rem',
                        px: '0.5rem',
                        py: '0.375rem',
                        'stepper-icon-size': '0.75rem',
                        'stepper-size': '1.75rem',
                        'textarea-min-height': '4rem',
                        'wrapper-gap': '0.25rem',
                    },
                },
                variants: {
                    filled: { bg: 'var(--color-surface-700)', 'border-color': 'transparent' },
                    ghost: { bg: 'transparent', 'border-color': 'transparent' },
                    outline: { bg: 'transparent' },
                },
            },
            {
                base: {
                    gap: '0',
                    'list-bg': 'var(--color-surface-700)',
                    'list-border-color': 'transparent',
                    'list-border-width': '0',
                    'list-radius': '0.5rem',
                    'tab-badge-bg': 'var(--color-danger-500)',
                    'tab-badge-fg': 'var(--color-text-50)',
                    'tab-badge-font-weight': '600',
                    'tab-badge-max': '99',
                    'tab-bg': 'transparent',
                    'tab-disabled-opacity': '0.5',
                    'tab-fg': 'var(--color-text-600)',
                    'tab-font-weight': '500',
                    'tab-radius': '0.375rem',
                    'tab-transition-duration': '150ms',
                    'tab-transition-easing': 'ease-out',
                },
                colorSlots: { 'tab-hover-bg': '100', 'tab-selected-bg': '500', 'tab-selected-fg': 'text-on' },
                focusRing: { offset: '0' },
                name: 'tabs',
                sizes: {
                    lg: {
                        'list-gap': '0.375rem',
                        'list-padding': '0.375rem',
                        'panel-padding': '1.25rem',
                        'tab-badge-font-size': '0.75rem',
                        'tab-badge-min-width': '1.5rem',
                        'tab-badge-padding-x': '0.5rem',
                        'tab-badge-radius': '0.75rem',
                        'tab-font-size': '1rem',
                        'tab-gap': '0.625rem',
                        'tab-height': '2.75rem',
                        'tab-icon-size': '1.25rem',
                        'tab-px': '1.25rem',
                    },
                    md: {
                        'list-gap': '0.25rem',
                        'list-padding': '0.25rem',
                        'panel-padding': '1rem',
                        'tab-badge-font-size': '0.625rem',
                        'tab-badge-min-width': '1.25rem',
                        'tab-badge-padding-x': '0.375rem',
                        'tab-badge-radius': '0.625rem',
                        'tab-font-size': '0.875rem',
                        'tab-gap': '0.5rem',
                        'tab-height': '2.25rem',
                        'tab-icon-size': '1rem',
                        'tab-px': '1rem',
                    },
                    sm: {
                        'list-gap': '0.125rem',
                        'list-padding': '0.125rem',
                        'panel-padding': '0.75rem',
                        'tab-badge-font-size': '0.5rem',
                        'tab-badge-min-width': '1rem',
                        'tab-badge-padding-x': '0.25rem',
                        'tab-badge-radius': '0.5rem',
                        'tab-font-size': '0.75rem',
                        'tab-gap': '0.375rem',
                        'tab-height': '1.75rem',
                        'tab-icon-size': '0.875rem',
                        'tab-px': '0.75rem',
                    },
                },
            },
            {
                base: {
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    'item-badge-bg': 'var(--color-primary-500)',
                    'item-badge-fg': 'var(--color-text-50)',
                    'item-badge-max': '99',
                    'item-destructive-fg': 'var(--color-danger-500)',
                    'item-destructive-hover-bg': 'var(--color-danger-100)',
                    'item-disabled-opacity': '0.5',
                    'item-fg': 'var(--color-text-500)',
                    'item-longpress-haptic-duration': '200',
                    'item-longpress-threshold': '500',
                    'item-radius': '0.375rem',
                    'popover-animation-offset': '0.5rem',
                    'popover-animation-scale': '0.95',
                    'popover-offset': '4px',
                    radius: '0.5rem',
                    'section-header-fg': 'var(--color-text-700)',
                    'section-header-font-weight': '600',
                    'separator-color': 'var(--color-surface-600)',
                    'separator-height': '1px',
                    'separator-my': '0.25rem',
                    shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'shortcut-fg': 'var(--color-text-700)',
                    'submenu-delay': '200',
                    'submenu-indicator-color': 'var(--color-text-600)',
                    'submenu-offset': '4',
                    'submenu-skeleton-bg': 'var(--color-surface-600)',
                    'submenu-skeleton-count': '3',
                    'submenu-skeleton-radius': '0.25rem',
                },
                colorSlots: {
                    'item-focused-bg': '100',
                    'item-hover-bg': '100',
                    'item-pressed-bg': '200',
                    'item-selected-bg': '500',
                    'item-selected-fg': 'text-on',
                },
                name: 'menu',
                sizes: {
                    lg: {
                        'item-badge-font-size': '0.75rem',
                        'item-badge-min-width': '1.5rem',
                        'item-badge-padding-x': '0.5rem',
                        'item-badge-radius': '0.75rem',
                        'item-font-size': '1rem',
                        'item-gap': '0.625rem',
                        'item-height': '2.5rem',
                        'item-icon-size': '1.25rem',
                        'item-px': '1rem',
                        padding: '0.375rem',
                        'section-header-font-size': '0.875rem',
                        'section-header-px': '1rem',
                        'section-header-py': '0.625rem',
                        'shortcut-font-size': '0.875rem',
                        'submenu-indicator-size': '1.25rem',
                        'submenu-skeleton-gap': '0.375rem',
                        'submenu-skeleton-height': '2rem',
                    },
                    md: {
                        'item-badge-font-size': '0.625rem',
                        'item-badge-min-width': '1.25rem',
                        'item-badge-padding-x': '0.375rem',
                        'item-badge-radius': '0.625rem',
                        'item-font-size': '0.875rem',
                        'item-gap': '0.5rem',
                        'item-height': '2rem',
                        'item-icon-size': '1rem',
                        'item-px': '0.75rem',
                        padding: '0.25rem',
                        'section-header-font-size': '0.75rem',
                        'section-header-px': '0.75rem',
                        'section-header-py': '0.5rem',
                        'shortcut-font-size': '0.75rem',
                        'submenu-indicator-size': '1rem',
                        'submenu-skeleton-gap': '0.25rem',
                        'submenu-skeleton-height': '1.5rem',
                    },
                    sm: {
                        'item-badge-font-size': '0.5rem',
                        'item-badge-min-width': '1rem',
                        'item-badge-padding-x': '0.25rem',
                        'item-badge-radius': '0.5rem',
                        'item-font-size': '0.75rem',
                        'item-gap': '0.375rem',
                        'item-height': '1.75rem',
                        'item-icon-size': '0.875rem',
                        'item-px': '0.5rem',
                        padding: '0.125rem',
                        'section-header-font-size': '0.625rem',
                        'section-header-px': '0.5rem',
                        'section-header-py': '0.375rem',
                        'shortcut-font-size': '0.625rem',
                        'submenu-indicator-size': '0.875rem',
                        'submenu-skeleton-gap': '0.125rem',
                        'submenu-skeleton-height': '1.25rem',
                    },
                },
            },
            {
                base: {
                    'actions-margin-top': '1rem',
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    'button-cancel-bg': 'var(--color-surface-600)',
                    'button-cancel-fg': 'var(--color-text-500)',
                    'button-confirm-bg': 'var(--color-danger-500)',
                    'button-confirm-fg': 'var(--color-text-50)',
                    'button-gap': '0.5rem',
                    'button-padding-x': '1rem',
                    'button-padding-y': '0.5rem',
                    'button-radius': '0.375rem',
                    'description-fg': 'var(--color-text-600)',
                    'description-margin-top': '0.5rem',
                    fg: 'var(--color-text-500)',
                    'font-size': '0.875rem',
                    'header-font-size': '1rem',
                    'header-font-weight': '600',
                    'max-width': '24rem',
                    'overlay-bg': 'rgb(0 0 0 / 0.5)',
                    padding: '1.5rem',
                    radius: '0.5rem',
                    shadow: '0 8px 16px rgb(0 0 0 / 0.2)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                    'z-index': '100',
                },
                colorSlots: {},
                name: 'dialog',
                sizes: {},
            },
            {
                base: {
                    'animation-duration': '200ms',
                    'animation-easing': 'ease-out',
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    'indicator-rotation': '180deg',
                    'item-border-color': 'var(--color-surface-600)',
                    'item-border-width': '1px',
                    'panel-bg': 'var(--color-surface-700)',
                    'panel-fg': 'var(--color-text-500)',
                    radius: '0.5rem',
                },
                colorSlots: {},
                name: 'accordion',
                sizes: {
                    lg: { 'panel-font-size': '1rem', 'panel-padding': '1.25rem' },
                    md: { 'panel-font-size': '0.875rem', 'panel-padding': '1rem' },
                    sm: { 'panel-font-size': '0.75rem', 'panel-padding': '0.75rem' },
                },
            },
            {
                asyncStyles: {
                    failure: { 'icon-animation': 'shake 0.3s ease-in-out' },
                    idle: { 'icon-animation': 'none' },
                    loading: { 'icon-animation': 'spin 0.8s ease-in-out infinite' },
                    success: { 'icon-animation': 'none' },
                },
                base: {
                    bg: 'transparent',
                    'disabled-opacity': '0.5',
                    fg: 'var(--color-text-500)',
                    'font-weight': '500',
                    'hover-bg': 'var(--color-surface-600)',
                    'icon-color': 'var(--color-text-600)',
                    'indicator-color': 'var(--color-text-600)',
                    'pressed-bg': 'var(--color-surface-500)',
                    radius: '0',
                },
                colorInherit: 'accordion',
                colorSlots: {
                    'hover-bg': '100',
                    'indicator-color': '500',
                    'pressed-bg': '200',
                },
                name: 'accordion-trigger',
                sizes: {
                    lg: {
                        'font-size': '1rem',
                        gap: '0.625rem',
                        height: '3.5rem',
                        'icon-size': '1.25rem',
                        'indicator-size': '1.25rem',
                        px: '1.25rem',
                    },
                    md: {
                        'font-size': '0.875rem',
                        gap: '0.5rem',
                        height: '3rem',
                        'icon-size': '1rem',
                        'indicator-size': '1rem',
                        px: '1rem',
                    },
                    sm: {
                        'font-size': '0.75rem',
                        gap: '0.375rem',
                        height: '2.5rem',
                        'icon-size': '0.875rem',
                        'indicator-size': '0.875rem',
                        px: '0.75rem',
                    },
                },
                variants: {
                    filled: { bg: 'var(--color-surface-600)', radius: '0.375rem' },
                    ghost: { bg: 'transparent', 'hover-bg': 'var(--color-surface-600)' },
                },
            },
            {
                base: {
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    gap: '0.5rem',
                    'group-gap': '0.25rem',
                    padding: '0.25rem',
                    radius: '0.5rem',
                    'separator-color': 'var(--color-surface-500)',
                    'separator-length': '1.25rem',
                    'separator-margin': '0.25rem',
                    'separator-thickness': '1px',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorSlots: {},
                name: 'toolbar',
                sizes: {
                    lg: { 'separator-length': '1.5rem' },
                    md: { 'separator-length': '1.25rem' },
                    sm: { 'separator-length': '1rem' },
                },
                variants: {
                    ghost: { bg: 'transparent', 'border-color': 'transparent', 'border-width': '0' },
                    outline: { bg: 'transparent' },
                    solid: {},
                },
            },
            {
                base: {
                    bg: 'transparent',
                    'disabled-opacity': '0.5',
                    fg: 'var(--color-text-500)',
                    'font-weight': '500',
                    radius: '0.375rem',
                    'selection-indicator-bg': 'var(--color-primary-100)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorInherit: 'toolbar',
                colorSlots: {
                    'focused-bg': '100',
                    'hover-bg': '100',
                    'pressed-bg': '200',
                    'selected-bg': '500',
                    'selected-fg': 'text-on',
                    'selection-indicator-bg': '100',
                },
                longpress: {
                    animation: 'pulse 1s ease-in-out infinite',
                    background:
                        'conic-gradient(from 0deg, var(--focus-ring-color) calc(var(--toolbar-item-longpress-progress) * 360deg), transparent 0deg)',
                    'border-radius': 'inherit',
                    content: "''",
                    inset: '-4px',
                    opacity: '0.5',
                    'pointer-events': 'none',
                    position: 'absolute',
                },
                name: 'toolbar-item',
                sizes: {
                    lg: {
                        'font-size': '1rem',
                        gap: '0.5rem',
                        height: '2.5rem',
                        'icon-size': '1.25rem',
                        'min-width': '2.5rem',
                        px: '0.75rem',
                    },
                    md: {
                        'font-size': '0.875rem',
                        gap: '0.375rem',
                        height: '2rem',
                        'icon-size': '1rem',
                        'min-width': '2rem',
                        px: '0.625rem',
                    },
                    sm: {
                        'font-size': '0.75rem',
                        gap: '0.25rem',
                        height: '1.75rem',
                        'icon-size': '0.875rem',
                        'min-width': '1.75rem',
                        px: '0.5rem',
                    },
                },
            },
            {
                base: {
                    'animation-duration': '200ms',
                    'animation-easing': 'ease-out',
                    gap: '0.125rem',
                    indent: '1.5rem',
                },
                colorSlots: {},
                name: 'tree',
                sizes: {
                    lg: { 'font-size': '1rem', gap: '0.1875rem', indent: '1.75rem' },
                    md: { 'font-size': '0.875rem', gap: '0.125rem', indent: '1.5rem' },
                    sm: { 'font-size': '0.75rem', gap: '0.0625rem', indent: '1.25rem' },
                },
            },
            {
                base: {
                    bg: 'transparent',
                    'disabled-opacity': '0.5',
                    fg: 'var(--color-text-500)',
                    'font-weight': '500',
                    'indicator-color': 'var(--color-text-600)',
                    'indicator-rotation': '90deg',
                    radius: '0.375rem',
                },
                colorInherit: 'tree',
                colorSlots: {
                    'hover-bg': '100',
                    'pressed-bg': '200',
                    'selected-bg': '500',
                    'selected-fg': 'text-on',
                },
                name: 'tree-item-content',
                sizes: {
                    lg: {
                        'actions-gap': '0.5rem',
                        'font-size': '1rem',
                        gap: '0.625rem',
                        height: '2.5rem',
                        'icon-size': '1.25rem',
                        'indicator-size': '1.25rem',
                        px: '0.75rem',
                    },
                    md: {
                        'actions-gap': '0.375rem',
                        'font-size': '0.875rem',
                        gap: '0.5rem',
                        height: '2rem',
                        'icon-size': '1rem',
                        'indicator-size': '1rem',
                        px: '0.625rem',
                    },
                    sm: {
                        'actions-gap': '0.25rem',
                        'font-size': '0.75rem',
                        gap: '0.375rem',
                        height: '1.75rem',
                        'icon-size': '0.875rem',
                        'indicator-size': '0.875rem',
                        px: '0.5rem',
                    },
                },
            },
            // --- TagGroup Components ---
            {
                base: {
                    'animation-duration': '150ms',
                    'animation-easing': 'ease-out',
                    gap: '0.5rem',
                },
                colorSlots: {},
                name: 'tag-group',
                sizes: {
                    lg: { gap: '0.625rem' },
                    md: { gap: '0.5rem' },
                    sm: { gap: '0.375rem' },
                },
            },
            {
                base: {
                    fg: 'var(--color-text-500)',
                    'font-size': '0.75rem',
                    'font-weight': '500',
                    'margin-bottom': '0.375rem',
                },
                colorSlots: {},
                name: 'tag-group-label',
                sizes: {
                    lg: { 'font-size': '0.875rem', 'margin-bottom': '0.5rem' },
                    md: { 'font-size': '0.75rem', 'margin-bottom': '0.375rem' },
                    sm: { 'font-size': '0.625rem', 'margin-bottom': '0.25rem' },
                },
            },
            {
                base: { gap: '0.5rem' },
                colorSlots: {},
                name: 'tag-group-list',
                sizes: {
                    lg: { gap: '0.625rem' },
                    md: { gap: '0.5rem' },
                    sm: { gap: '0.375rem' },
                },
            },
            {
                base: {
                    bg: 'transparent',
                    'border-color': 'var(--color-text-200)',
                    'border-width': '1px',
                    'disabled-opacity': '0.5',
                    fg: 'var(--color-text-600)',
                    'font-weight': '500',
                    radius: '9999px',
                },
                colorInherit: 'tag-group',
                colorSlots: {
                    bg: '100',
                    'border-color': '200',
                    fg: '700',
                    'hover-bg': '200',
                    'pressed-bg': '300',
                    'selected-bg': '500',
                    'selected-fg': 'text-on',
                },
                name: 'tag',
                sizes: {
                    lg: { 'font-size': '0.875rem', gap: '0.5rem', height: '2rem', 'icon-size': '1rem', px: '0.875rem' },
                    md: {
                        'font-size': '0.75rem',
                        gap: '0.375rem',
                        height: '1.5rem',
                        'icon-size': '0.875rem',
                        px: '0.625rem',
                    },
                    sm: {
                        'font-size': '0.625rem',
                        gap: '0.25rem',
                        height: '1.25rem',
                        'icon-size': '0.75rem',
                        px: '0.5rem',
                    },
                },
                variants: {
                    outline: {
                        bg: 'transparent',
                        'border-width': '1px',
                    },
                    solid: {
                        'border-width': '0',
                    },
                },
            },
            {
                base: {
                    fg: 'var(--color-text-400)',
                    'hover-bg': 'var(--color-text-100)',
                    'hover-fg': 'var(--color-text-600)',
                    'margin-left': '0.25rem',
                    radius: '9999px',
                },
                colorInherit: 'tag-group',
                colorSlots: {
                    fg: '400',
                    'hover-bg': '200',
                    'hover-fg': '600',
                },
                name: 'tag-remove',
                sizes: {
                    lg: { 'margin-left': '0.375rem', size: '1rem' },
                    md: { 'margin-left': '0.25rem', size: '0.875rem' },
                    sm: { 'margin-left': '0.125rem', size: '0.75rem' },
                },
            },
            // --- Table Components ---
            {
                base: {
                    'animation-duration': '150ms',
                    'animation-easing': 'ease-out',
                    bg: 'var(--color-surface-50)',
                    'border-color': 'var(--color-text-200)',
                    'border-width': '1px',
                    fg: 'var(--color-text-700)',
                    'font-weight': '400',
                    radius: '0.5rem',
                },
                colorSlots: {},
                name: 'table',
                sizes: {
                    lg: { 'font-size': '1rem' },
                    md: { 'font-size': '0.875rem' },
                    sm: { 'font-size': '0.75rem' },
                },
            },
            {
                base: {
                    bg: 'var(--color-surface-100)',
                    'border-color': 'var(--color-text-200)',
                    'border-width': '1px',
                    fg: 'var(--color-text-600)',
                },
                colorSlots: {},
                name: 'table-header',
                sizes: {},
            },
            {
                base: { bg: 'transparent' },
                colorSlots: {},
                name: 'table-body',
                sizes: {},
            },
            {
                base: {
                    bg: 'transparent',
                    'border-color': 'var(--color-text-100)',
                    'border-width': '1px',
                    'disabled-opacity': '0.5',
                },
                colorInherit: 'table',
                colorSlots: {
                    'hover-bg': '100',
                    'selected-bg': '200',
                    'selected-fg': '800',
                },
                name: 'table-row',
                sizes: {},
            },
            {
                base: {},
                colorSlots: {},
                name: 'table-cell',
                sizes: {
                    lg: { 'font-size': '1rem', px: '1rem', py: '0.75rem' },
                    md: { 'font-size': '0.875rem', px: '0.75rem', py: '0.5rem' },
                    sm: { 'font-size': '0.75rem', px: '0.5rem', py: '0.375rem' },
                },
            },
            {
                base: {
                    'font-weight': '600',
                },
                colorInherit: 'table',
                colorSlots: {
                    'hover-bg': '100',
                },
                name: 'table-column',
                sizes: {
                    lg: { 'font-size': '0.875rem', gap: '0.5rem', px: '1rem', py: '0.75rem' },
                    md: { 'font-size': '0.75rem', gap: '0.375rem', px: '0.75rem', py: '0.5rem' },
                    sm: { 'font-size': '0.625rem', gap: '0.25rem', px: '0.5rem', py: '0.375rem' },
                },
            },
            {
                base: {
                    'border-color': 'var(--color-text-300)',
                    radius: '0.25rem',
                },
                colorInherit: 'table',
                colorSlots: {
                    'checked-bg': '500',
                    'checked-fg': 'text-on',
                },
                name: 'table-checkbox',
                sizes: {
                    lg: { size: '1.25rem' },
                    md: { size: '1rem' },
                    sm: { size: '0.875rem' },
                },
            },
            {
                base: {
                    'active-bg': 'var(--color-primary-400)',
                    bg: 'var(--color-text-200)',
                    'hover-bg': 'var(--color-primary-300)',
                    width: '4px',
                },
                colorSlots: {},
                name: 'table-resizer',
                sizes: {},
            },
            {
                base: {
                    color: 'var(--color-text-400)',
                },
                colorSlots: {},
                name: 'table-sort-indicator',
                sizes: {
                    lg: { size: '1rem' },
                    md: { size: '0.875rem' },
                    sm: { size: '0.75rem' },
                },
            },
            {
                base: {
                    fg: 'var(--color-text-400)',
                },
                colorSlots: {},
                name: 'table-empty',
                sizes: {
                    lg: { py: '3rem' },
                    md: { py: '2rem' },
                    sm: { py: '1.5rem' },
                },
            },
            {
                base: { overflow: 'auto' },
                colorSlots: {},
                name: 'table-resizable',
                sizes: {},
            },
            // --- ColorPicker Component ---
            {
                base: {
                    'alpha-pattern': 'repeating-conic-gradient(#808080 0 25%, #fff 0 50%)',
                    'alpha-pattern-size': '8px 8px',
                    'description-color': 'var(--color-text-600)',
                    'disabled-opacity': '0.5',
                    'error-color': 'var(--color-danger-400)',
                    'field-bg': 'var(--color-surface-600)',
                    'field-border-color': 'var(--color-text-800)',
                    'field-fg': 'var(--color-text-500)',
                    'field-hover-border': 'var(--color-text-600)',
                    'field-invalid-border': 'var(--color-danger-500)',
                    'label-color': 'var(--color-text-500)',
                    'slider-output-color': 'var(--color-text-500)',
                    'swatch-border-color': 'var(--color-text-700)',
                    'thumb-bg': 'white',
                    'thumb-border-color': 'white',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorSlots: {},
                name: 'color-picker',
                sizes: {
                    lg: {
                        'area-height': '10rem',
                        'area-radius': '0.5rem',
                        'area-width': '10rem',
                        'description-font-size': '0.875rem',
                        'error-font-size': '0.875rem',
                        'field-border-width': '1px',
                        'field-font-size': '1rem',
                        'field-height': '2.5rem',
                        'field-px': '0.75rem',
                        'field-radius': '0.375rem',
                        'field-width': '8rem',
                        gap: '1rem',
                        'label-font-size': '0.875rem',
                        'label-font-weight': '500',
                        'slider-height': '1rem',
                        'slider-output-font-size': '0.875rem',
                        'slider-output-font-weight': '500',
                        'slider-radius': '9999px',
                        'slider-width': '10rem',
                        'swatch-border-width': '2px',
                        'swatch-gap': '0.5rem',
                        'swatch-hover-scale': '1.1',
                        'swatch-radius': '0.25rem',
                        'swatch-size': '1.5rem',
                        'thumb-border-width': '2px',
                        'thumb-dragging-scale': '1.15',
                        'thumb-dragging-shadow': '0 2px 8px rgb(0 0 0 / 0.3)',
                        'thumb-hover-scale': '1.1',
                        'thumb-radius': '9999px',
                        'thumb-shadow': '0 1px 4px rgb(0 0 0 / 0.2)',
                        'thumb-size': '1.25rem',
                        'wheel-size': '10rem',
                    },
                    md: {
                        'area-height': '8rem',
                        'area-radius': '0.375rem',
                        'area-width': '8rem',
                        'description-font-size': '0.75rem',
                        'error-font-size': '0.75rem',
                        'field-border-width': '1px',
                        'field-font-size': '0.875rem',
                        'field-height': '2rem',
                        'field-px': '0.625rem',
                        'field-radius': '0.25rem',
                        'field-width': '6rem',
                        gap: '0.75rem',
                        'label-font-size': '0.75rem',
                        'label-font-weight': '500',
                        'slider-height': '0.75rem',
                        'slider-output-font-size': '0.75rem',
                        'slider-output-font-weight': '500',
                        'slider-radius': '9999px',
                        'slider-width': '8rem',
                        'swatch-border-width': '1px',
                        'swatch-gap': '0.375rem',
                        'swatch-hover-scale': '1.1',
                        'swatch-radius': '0.25rem',
                        'swatch-size': '1.25rem',
                        'thumb-border-width': '2px',
                        'thumb-dragging-scale': '1.15',
                        'thumb-dragging-shadow': '0 2px 6px rgb(0 0 0 / 0.3)',
                        'thumb-hover-scale': '1.1',
                        'thumb-radius': '9999px',
                        'thumb-shadow': '0 1px 3px rgb(0 0 0 / 0.2)',
                        'thumb-size': '1rem',
                        'wheel-size': '8rem',
                    },
                    sm: {
                        'area-height': '6rem',
                        'area-radius': '0.25rem',
                        'area-width': '6rem',
                        'description-font-size': '0.625rem',
                        'error-font-size': '0.625rem',
                        'field-border-width': '1px',
                        'field-font-size': '0.75rem',
                        'field-height': '1.75rem',
                        'field-px': '0.5rem',
                        'field-radius': '0.25rem',
                        'field-width': '5rem',
                        gap: '0.5rem',
                        'label-font-size': '0.625rem',
                        'label-font-weight': '500',
                        'slider-height': '0.5rem',
                        'slider-output-font-size': '0.625rem',
                        'slider-output-font-weight': '500',
                        'slider-radius': '9999px',
                        'slider-width': '6rem',
                        'swatch-border-width': '1px',
                        'swatch-gap': '0.25rem',
                        'swatch-hover-scale': '1.1',
                        'swatch-radius': '0.125rem',
                        'swatch-size': '1rem',
                        'thumb-border-width': '2px',
                        'thumb-dragging-scale': '1.1',
                        'thumb-dragging-shadow': '0 1px 4px rgb(0 0 0 / 0.3)',
                        'thumb-hover-scale': '1.05',
                        'thumb-radius': '9999px',
                        'thumb-shadow': '0 1px 2px rgb(0 0 0 / 0.2)',
                        'thumb-size': '0.875rem',
                        'wheel-size': '6rem',
                    },
                },
            },
            // --- Progress Component ---
            {
                base: {
                    'animation-duration': '300ms',
                    'animation-easing': 'ease-out',
                    'disabled-opacity': '0.5',
                    'indeterminate-animation': 'progress-indeterminate 1.5s ease-in-out infinite',
                    'indeterminate-width': '35%',
                    width: '100%',
                },
                colorSlots: {
                    'circle-icon-color': '500',
                    'circle-indicator-stroke': '500',
                    'circle-track-stroke': '200',
                    'circle-value-fg': '700',
                    'fill-bg': '500',
                    'label-fg': '700',
                    'track-bg': '200',
                    'value-fg': '700',
                },
                name: 'progress',
                sizes: {
                    lg: {
                        'circle-icon-size': '1.25rem',
                        'circle-size': '3.5rem',
                        'circle-value-font-size': '0.875rem',
                        'circle-value-font-weight': '600',
                        'fill-radius': '9999px',
                        gap: '0.625rem',
                        'label-font-size': '1rem',
                        'label-font-weight': '500',
                        'track-height': '0.625rem',
                        'track-radius': '9999px',
                        'value-font-size': '1rem',
                        'value-font-weight': '500',
                    },
                    md: {
                        'circle-icon-size': '1rem',
                        'circle-size': '2.75rem',
                        'circle-value-font-size': '0.75rem',
                        'circle-value-font-weight': '500',
                        'fill-radius': '9999px',
                        gap: '0.5rem',
                        'label-font-size': '0.875rem',
                        'label-font-weight': '500',
                        'track-height': '0.5rem',
                        'track-radius': '9999px',
                        'value-font-size': '0.875rem',
                        'value-font-weight': '500',
                    },
                    sm: {
                        'circle-icon-size': '0.875rem',
                        'circle-size': '2rem',
                        'circle-value-font-size': '0.625rem',
                        'circle-value-font-weight': '500',
                        'fill-radius': '9999px',
                        gap: '0.375rem',
                        'label-font-size': '0.75rem',
                        'label-font-weight': '500',
                        'track-height': '0.375rem',
                        'track-radius': '9999px',
                        'value-font-size': '0.75rem',
                        'value-font-weight': '500',
                    },
                },
            },
            // --- DatePicker Component ---
            {
                base: {
                    'calendar-bg': 'var(--color-surface-700)',
                    'cell-hover-bg': 'var(--color-surface-600)',
                    'cell-outside-fg': 'var(--color-text-700)',
                    'cell-pressed-bg': 'var(--color-surface-500)',
                    'cell-today-ring-width': '2px',
                    'description-fg': 'var(--color-text-600)',
                    'disabled-opacity': '0.5',
                    'error-fg': 'var(--color-danger-400)',
                    'field-bg': 'var(--color-surface-600)',
                    'field-border-color': 'var(--color-text-800)',
                    'field-border-width': '1px',
                    'field-fg': 'var(--color-text-500)',
                    'grid-header-fg': 'var(--color-text-600)',
                    'grid-header-font-weight': '500',
                    'header-button-hover-bg': 'var(--color-surface-600)',
                    'header-button-pressed-bg': 'var(--color-surface-500)',
                    'header-title-fg': 'var(--color-text-500)',
                    'header-title-font-weight': '600',
                    'label-fg': 'var(--color-text-500)',
                    'label-font-weight': '500',
                    'popover-animation-offset': '0.5rem',
                    'popover-animation-scale': '0.95',
                    'popover-bg': 'var(--color-surface-700)',
                    'popover-border-color': 'var(--color-surface-600)',
                    'popover-border-width': '1px',
                    'popover-shadow': '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'segment-placeholder-fg': 'var(--color-text-700)',
                    'time-label-fg': 'var(--color-text-500)',
                    'time-label-font-weight': '500',
                    'transition-duration': '150ms',
                    'trigger-bg': 'transparent',
                    'trigger-border-color': 'transparent',
                    'trigger-border-width': '0',
                    'trigger-hover-bg': 'var(--color-surface-600)',
                    'trigger-pressed-bg': 'var(--color-surface-500)',
                },
                colorSlots: {
                    'cell-selected-bg': '500',
                    'cell-selected-fg': 'text-on',
                    'cell-today-ring-color': '400',
                    'segment-focus-bg': '100',
                    'segment-focus-fg': '700',
                },
                name: 'date-picker',
                sizes: {
                    lg: {
                        'calendar-padding': '1rem',
                        'calendar-radius': '0.5rem',
                        'calendar-width': '18rem',
                        'cell-font-size': '0.875rem',
                        'cell-radius': '0.375rem',
                        'cell-size': '2.5rem',
                        'description-font-size': '0.875rem',
                        'error-font-size': '0.875rem',
                        'field-gap': '0.375rem',
                        'field-height': '2.5rem',
                        'field-px': '0.75rem',
                        'field-radius': '0.375rem',
                        gap: '0.625rem',
                        'grid-header-font-size': '0.75rem',
                        'grid-header-padding': '0.5rem',
                        'header-button-icon-size': '1.25rem',
                        'header-button-radius': '0.375rem',
                        'header-button-size': '2rem',
                        'header-mb': '0.75rem',
                        'header-title-font-size': '1rem',
                        'label-font-size': '0.875rem',
                        'popover-offset': '8',
                        'popover-padding': '1rem',
                        'popover-radius': '0.5rem',
                        'range-calendar-gap': '1rem',
                        'segment-font-size': '0.875rem',
                        'segment-px': '0.125rem',
                        'segment-radius': '0.25rem',
                        'time-gap': '0.5rem',
                        'time-label-font-size': '0.75rem',
                        'trigger-gap': '0.5rem',
                        'trigger-icon-size': '1.25rem',
                        'trigger-radius': '0.375rem',
                        'trigger-size': '2.5rem',
                    },
                    md: {
                        'calendar-padding': '0.75rem',
                        'calendar-radius': '0.375rem',
                        'calendar-width': '16rem',
                        'cell-font-size': '0.75rem',
                        'cell-radius': '0.25rem',
                        'cell-size': '2rem',
                        'description-font-size': '0.75rem',
                        'error-font-size': '0.75rem',
                        'field-gap': '0.25rem',
                        'field-height': '2rem',
                        'field-px': '0.625rem',
                        'field-radius': '0.25rem',
                        gap: '0.5rem',
                        'grid-header-font-size': '0.625rem',
                        'grid-header-padding': '0.375rem',
                        'header-button-icon-size': '1rem',
                        'header-button-radius': '0.25rem',
                        'header-button-size': '1.75rem',
                        'header-mb': '0.5rem',
                        'header-title-font-size': '0.875rem',
                        'label-font-size': '0.75rem',
                        'popover-offset': '6',
                        'popover-padding': '0.75rem',
                        'popover-radius': '0.375rem',
                        'range-calendar-gap': '0.75rem',
                        'segment-font-size': '0.75rem',
                        'segment-px': '0.0625rem',
                        'segment-radius': '0.125rem',
                        'time-gap': '0.375rem',
                        'time-label-font-size': '0.625rem',
                        'trigger-gap': '0.375rem',
                        'trigger-icon-size': '1rem',
                        'trigger-radius': '0.25rem',
                        'trigger-size': '2rem',
                    },
                    sm: {
                        'calendar-padding': '0.5rem',
                        'calendar-radius': '0.25rem',
                        'calendar-width': '14rem',
                        'cell-font-size': '0.625rem',
                        'cell-radius': '0.25rem',
                        'cell-size': '1.75rem',
                        'description-font-size': '0.625rem',
                        'error-font-size': '0.625rem',
                        'field-gap': '0.125rem',
                        'field-height': '1.75rem',
                        'field-px': '0.5rem',
                        'field-radius': '0.25rem',
                        gap: '0.375rem',
                        'grid-header-font-size': '0.5rem',
                        'grid-header-padding': '0.25rem',
                        'header-button-icon-size': '0.875rem',
                        'header-button-radius': '0.25rem',
                        'header-button-size': '1.5rem',
                        'header-mb': '0.375rem',
                        'header-title-font-size': '0.75rem',
                        'label-font-size': '0.625rem',
                        'popover-offset': '4',
                        'popover-padding': '0.5rem',
                        'popover-radius': '0.25rem',
                        'range-calendar-gap': '0.5rem',
                        'segment-font-size': '0.625rem',
                        'segment-px': '0.0625rem',
                        'segment-radius': '0.125rem',
                        'time-gap': '0.25rem',
                        'time-label-font-size': '0.5rem',
                        'trigger-gap': '0.25rem',
                        'trigger-icon-size': '0.875rem',
                        'trigger-radius': '0.25rem',
                        'trigger-size': '1.75rem',
                    },
                },
            },
            // --- Drawer Component ---
            // Slots consumed by drawer.tsx - ONLY these keys are valid
            {
                base: {
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    'button-gap': '0.75rem',
                    'description-fg': 'var(--color-text-600)',
                    'description-margin-top': '0.5rem',
                    fg: 'var(--color-text-500)',
                    'handle-bg': 'var(--color-text-700)',
                    'handle-height': '0.25rem',
                    'handle-margin': '0.75rem',
                    'handle-width': '3rem',
                    'header-font-size': '1.125rem',
                    'header-font-weight': '600',
                    'overlay-bg': 'rgb(0 0 0 / 0.5)',
                    radius: '0.75rem',
                    'shadow-bottom': '0 -8px 24px rgb(0 0 0 / 0.25)',
                    'shadow-left': '8px 0 24px rgb(0 0 0 / 0.25)',
                    'shadow-right': '-8px 0 24px rgb(0 0 0 / 0.25)',
                    'shadow-top': '0 8px 24px rgb(0 0 0 / 0.25)',
                    'z-index': '100',
                },
                colorSlots: {},
                name: 'drawer',
                sizes: {
                    lg: {
                        'font-size': '1rem',
                        'max-height': '90vh',
                        'max-width': '32rem',
                        padding: '1.5rem',
                    },
                    md: {
                        'font-size': '0.875rem',
                        'max-height': '75vh',
                        'max-width': '24rem',
                        padding: '1.25rem',
                    },
                    sm: {
                        'font-size': '0.75rem',
                        'max-height': '50vh',
                        'max-width': '18rem',
                        padding: '1rem',
                    },
                },
            },
        ],
        focus: { color: { name: 'primary', step: 400 }, offset: '2px', width: '2px', z: '10' },
        fonts: { mono: 'monospace', ui: 'system-ui' },
        interaction: { announceDuration: 1000, haptic: true, hapticDuration: 200, longPressThreshold: 500 },
        stateShifts: {
            disabled: { alpha: -0.4, chroma: -0.1, hue: 0, lightness: 0 },
            focused: { alpha: 0, chroma: 0.01, hue: 0, lightness: 0.03 },
            hovered: { alpha: 0, chroma: 0, hue: 0, lightness: 0.05 },
            pressed: { alpha: 0, chroma: 0.02, hue: 0, lightness: -0.05 },
            selected: { alpha: 0, chroma: 0.03, hue: 0, lightness: -0.08 },
        },
        toastStyles: [
            {
                base: {
                    // Action
                    'action-color': 'currentColor',
                    'action-weight': '500',
                    // Appearance
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    'content-gap': '0.125rem',
                    // Description
                    'description-color': 'var(--color-text-600)',
                    'description-size': '0.75rem',
                    'dismiss-color': 'var(--color-text-600)',
                    'dismiss-hover-bg': 'var(--color-surface-600)',
                    'dismiss-icon-size': '1rem',
                    'dismiss-radius': '0.25rem',
                    // Dismiss
                    'dismiss-size': '1.5rem',
                    fg: 'var(--color-text-500)',
                    'focus-ring-color': 'var(--color-primary-400)',
                    'font-size': '0.875rem',
                    gap: '0.75rem',
                    'icon-color': 'var(--color-text-600)',
                    // Icon
                    'icon-size': '1.25rem',
                    'inner-gap': '0.75rem',
                    // Layout
                    'max-width': '24rem',
                    offset: '1rem',
                    'padding-x': '1rem',
                    'padding-y': '0.75rem',
                    radius: '0.5rem',
                    shadow: '0 4px 12px rgb(0 0 0 / 0.15)',
                    // Title
                    'title-color': 'inherit',
                    'title-weight': '600',
                    'z-index': '9999',
                },
                name: 'default',
                progress: { bg: 'var(--color-primary-500)', height: '3px', radius: '0 0 0.5rem 0.5rem' },
                transition: { duration: '200ms', easing: 'ease-out' },
                types: {
                    error: {
                        bg: 'var(--color-danger-600)',
                        'border-color': 'var(--color-danger-700)',
                        'dismiss-color': 'var(--color-text-50)',
                        'dismiss-hover-bg': 'var(--color-danger-500)',
                        fg: 'var(--color-text-50)',
                        'icon-color': 'var(--color-text-50)',
                    },
                    info: {
                        bg: 'var(--color-surface-700)',
                        'border-color': 'var(--color-primary-500)',
                        fg: 'var(--color-text-500)',
                        'icon-color': 'var(--color-primary-400)',
                    },
                    success: {
                        bg: 'var(--color-success-600)',
                        'border-color': 'var(--color-success-700)',
                        'dismiss-color': 'var(--color-text-50)',
                        'dismiss-hover-bg': 'var(--color-success-500)',
                        fg: 'var(--color-text-50)',
                        'icon-color': 'var(--color-text-50)',
                    },
                    warning: {
                        bg: 'var(--color-warning-500)',
                        'border-color': 'var(--color-warning-600)',
                        'dismiss-color': 'var(--color-surface-900)',
                        'dismiss-hover-bg': 'var(--color-warning-400)',
                        fg: 'var(--color-surface-900)',
                        'icon-color': 'var(--color-surface-900)',
                    },
                },
            },
            {
                base: {
                    // Action
                    'action-color': 'currentColor',
                    'action-weight': '500',
                    // Appearance
                    bg: 'var(--color-surface-800)',
                    'border-color': 'transparent',
                    'border-width': '0',
                    'content-gap': '0.0625rem',
                    // Description
                    'description-color': 'var(--color-text-300)',
                    'description-size': '0.75rem',
                    'dismiss-color': 'var(--color-text-400)',
                    'dismiss-hover-bg': 'var(--color-surface-700)',
                    'dismiss-icon-size': '0.875rem',
                    'dismiss-radius': '0.25rem',
                    // Dismiss
                    'dismiss-size': '1.25rem',
                    fg: 'var(--color-text-50)',
                    'focus-ring-color': 'var(--color-primary-400)',
                    'font-size': '0.875rem',
                    gap: '0.5rem',
                    'icon-color': 'var(--color-text-400)',
                    // Icon
                    'icon-size': '1rem',
                    'inner-gap': '0.5rem',
                    // Layout
                    'max-width': '20rem',
                    offset: '0.75rem',
                    'padding-x': '0.875rem',
                    'padding-y': '0.625rem',
                    radius: '0.375rem',
                    shadow: '0 2px 8px rgb(0 0 0 / 0.2)',
                    // Title
                    'title-color': 'inherit',
                    'title-weight': '500',
                    'z-index': '9999',
                },
                name: 'compact',
                transition: { duration: '150ms', easing: 'ease-out' },
            },
        ],
        tooltipGroup: { boundary: 'viewport', closeDelay: 0, openDelay: 300, timeout: 200 },
        tooltipStyles: [
            {
                arrow: {
                    color: 'var(--tooltip-bg)',
                    height: '7px',
                    staticOffset: '8px',
                    tipRadius: '1px',
                    width: '14px',
                },
                base: {
                    bg: 'var(--color-surface-800)',
                    'border-color': 'transparent',
                    'border-width': '0',
                    fg: 'var(--color-text-50)',
                    'font-size': '0.875rem',
                    'max-width': '20rem',
                    'padding-x': '0.75rem',
                    'padding-y': '0.5rem',
                    radius: '0.375rem',
                    shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'z-index': '50',
                },
                name: 'default',
                transition: {
                    duration: '150ms',
                    easing: 'ease-out',
                    initialOpacity: '0',
                    initialTransform: 'translateY(-4px) scale(0.98)',
                },
            },
            {
                arrow: {
                    color: 'var(--color-danger-600)',
                    height: '7px',
                    stroke: 'var(--color-danger-800)',
                    strokeWidth: '1px',
                    width: '14px',
                },
                base: {
                    bg: 'var(--color-danger-600)',
                    'border-color': 'var(--color-danger-800)',
                    'border-width': '1px',
                    fg: 'var(--color-text-50)',
                    'font-size': '0.875rem',
                    'max-width': '20rem',
                    'padding-x': '0.75rem',
                    'padding-y': '0.5rem',
                    radius: '0.375rem',
                    shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'z-index': '50',
                },
                name: 'error',
                transition: {
                    duration: '120ms',
                    easing: 'ease-in-out',
                    initialOpacity: '0',
                    initialTransform: 'scale(0.95)',
                },
            },
        ],
    },
} as const);

// --- [ENTRY_POINT] -----------------------------------------------------------

const baseConfig = Effect.runSync(
    createConfig({
        mode: 'app',
        name: B.app.name,
        port: B.app.port,
        root: APP_ROOT,
    }),
);
export default defineConfig({
    ...baseConfig,
    plugins: [
        defineTheme(B.theme as unknown as ThemeConfig, ['src/main.css']),
        ...devtoolsPlugin({ app: B.app.name }),
        ...(baseConfig.plugins ?? []),
    ],
});
