/// <reference types="vite/client" />
/**
 * Test harness Vite config: Dracula theme + Button ComponentSpec.
 * Validates theme generation + component wiring pipeline.
 */
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { devtoolsPlugin } from '@parametric-portal/devtools/vite-plugin';
import { defineTheme, type ThemeConfig } from '@parametric-portal/theme/theme';
import { Effect } from 'effect';
import { defineConfig } from 'vite';
import { createConfig } from '../../vite.factory.ts';

// --- [CONSTANTS] -------------------------------------------------------------

const APP_ROOT = dirname(fileURLToPath(import.meta.url));
const B = Object.freeze({
    app: { name: 'TestHarness', port: 3002 },
    theme: {
        animation: { enterScale: 0.95, exitScale: 0.95 },
        colors: {
            // Dracula palette → OKLCH
            accent: { c: 0.22, h: 340, l: 0.72 }, // Pink #ff79c6
            danger: { c: 0.25, h: 25, l: 0.65 }, // Red #ff5555
            primary: { c: 0.18, h: 290, l: 0.72 }, // Purple #bd93f9
            secondary: { c: 0.12, h: 195, l: 0.85 }, // Cyan #8be9fd
            success: { c: 0.25, h: 145, l: 0.85 }, // Green #50fa7b
            surface: { c: 0.02, h: 260, l: 0.22 }, // Background #282a36
            text: { c: 0.01, h: 90, l: 0.97 }, // Foreground #f8f8f2
            warning: { c: 0.15, h: 55, l: 0.82 }, // Orange #ffb86c
        },
        components: [
            {
                asyncStyles: {
                    failure: { 'icon-animation': 'shake 0.3s ease-in-out' },
                    idle: { 'icon-animation': 'none' },
                    loading: { 'icon-animation': 'spin 0.8s ease-in-out infinite' },
                    success: { 'icon-animation': 'none' },
                },
                base: {
                    'disabled-opacity': '0.5',
                    'font-size': '0.875rem',
                    'font-weight': '500',
                    gap: '0.5rem',
                    height: '2.5rem',
                    'icon-size': '1rem',
                    'pressed-scale': '0.98',
                    px: '1rem',
                    radius: '0.5rem',
                    shadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                    width: '8rem',
                },
                colorSlots: {
                    bg: '500',
                    'border-color': '500',
                    fg: 'text-on',
                    'hover-bg': 'hovered',
                    'pressed-bg': 'pressed',
                },
                longpress: {
                    animation: 'pulse 1s ease-in-out infinite',
                    background:
                        'conic-gradient(from 0deg, var(--focus-ring-color) calc(var(--button-longpress-progress) * 360deg), transparent 0deg)',
                    'border-radius': 'inherit',
                    content: "''",
                    inset: '-4px',
                    opacity: '0.5',
                    'pointer-events': 'none',
                    position: 'absolute',
                },
                name: 'button',
                sizes: {
                    lg: { 'font-size': '1rem', height: '3rem', 'icon-size': '1.25rem', px: '1.25rem', width: '10rem' },
                    md: {},
                    sm: {
                        'font-size': '0.75rem',
                        height: '2rem',
                        'icon-size': '0.875rem',
                        px: '0.75rem',
                        width: '6rem',
                    },
                },
                variants: {
                    ghost: { bg: 'transparent', 'border-color': 'transparent', 'hover-bg': '100', shadow: 'none' },
                    outline: { bg: 'transparent', 'border-width': '1px', shadow: 'none' },
                    solid: { 'border-color': 'transparent' },
                },
            },
            {
                base: {
                    'active-border': 'var(--color-primary-400)',
                    bg: 'var(--color-surface-600)',
                    'border-style': 'dashed',
                    'border-width': '2px',
                    'disabled-opacity': '0.5',
                    'error-border': 'var(--color-danger-500)',
                    height: '12rem',
                    'idle-border': 'var(--color-text-800)',
                    radius: '0.75rem',
                    'transition-duration': '150ms',
                    width: '100%',
                },
                colorSlots: {},
                name: 'file-upload',
                sizes: {},
            },
            {
                base: {
                    bg: 'var(--color-surface-700)',
                    height: '8rem',
                    'icon-color': 'var(--color-text-600)',
                    'icon-size': '2rem',
                    'meta-bg': 'oklch(0 0 0 / 0.5)',
                    'meta-fg': 'var(--color-text-50)',
                    'meta-font-size': '0.75rem',
                    'meta-padding': '0.5rem',
                    radius: '0.5rem',
                    width: '8rem',
                },
                colorSlots: {},
                name: 'file-preview',
                sizes: {},
            },
            {
                base: {
                    'disabled-opacity': '0.5',
                    gap: '0.5rem',
                    'label-color': 'var(--color-text-500)',
                    'label-size': '0.875rem',
                    'selected-bg': 'var(--color-primary-500)',
                    'thumb-bg': 'var(--color-text-50)',
                    'thumb-offset': '0.125rem',
                    'thumb-shadow': '0 1px 3px rgb(0 0 0 / 0.2)',
                    'thumb-size': '1.25rem',
                    'track-bg': 'var(--color-surface-600)',
                    'track-height': '1.5rem',
                    'track-radius': '0.75rem',
                    'track-width': '2.75rem',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorSlots: { 'selected-bg': '500' },
                name: 'switch',
                sizes: {
                    lg: {
                        'label-size': '1rem',
                        'thumb-size': '1.5rem',
                        'track-height': '1.75rem',
                        'track-width': '3.25rem',
                    },
                    md: {},
                    sm: {
                        'label-size': '0.75rem',
                        'thumb-size': '1rem',
                        'track-height': '1.25rem',
                        'track-width': '2.25rem',
                    },
                },
                variants: {
                    default: {},
                    outline: {
                        'thumb-bg': 'var(--color-text-600)',
                        'track-bg': 'transparent',
                    },
                },
            },
            {
                base: {
                    'border-color': 'var(--color-text-700)',
                    'border-width': '2px',
                    'box-bg': 'var(--color-surface-600)',
                    'box-radius': '0.25rem',
                    'box-size': '1.25rem',
                    'disabled-opacity': '0.5',
                    gap: '0.5rem',
                    'group-gap': '0.75rem',
                    'icon-color': 'var(--color-text-50)',
                    'icon-size': '0.875rem',
                    'invalid-border': 'var(--color-danger-500)',
                    'label-color': 'var(--color-text-500)',
                    'label-size': '0.875rem',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorInherit: 'checkbox-group',
                colorSlots: { 'selected-bg': '500', 'selected-border': '500' },
                name: 'checkbox',
                sizes: {
                    lg: { 'box-size': '1.5rem', 'icon-size': '1rem', 'label-size': '1rem' },
                    md: {},
                    sm: { 'box-size': '1rem', 'icon-size': '0.75rem', 'label-size': '0.75rem' },
                },
            },
            {
                base: {
                    gap: '0.75rem',
                },
                colorSlots: {},
                name: 'checkbox-group',
                sizes: {
                    lg: { gap: '1rem' },
                    md: {},
                    sm: { gap: '0.5rem' },
                },
            },
            {
                base: {
                    'description-color': 'var(--color-text-600)',
                    'description-size': '0.75rem',
                    'error-color': 'var(--color-danger-400)',
                    'error-size': '0.75rem',
                    gap: '0.75rem',
                    'label-color': 'var(--color-text-400)',
                    'label-size': '0.875rem',
                    'label-weight': '500',
                    'segmented-bg': 'var(--color-surface-700)',
                    'segmented-gap': '0.125rem',
                    'segmented-padding': '0.25rem',
                    'segmented-radius': '0.5rem',
                    'wrapper-gap': '0.5rem',
                },
                colorSlots: {},
                name: 'radio-group',
                sizes: {
                    lg: { 'description-size': '0.875rem', gap: '1rem', 'label-size': '1rem' },
                    md: {},
                    sm: { 'description-size': '0.625rem', gap: '0.5rem', 'label-size': '0.75rem' },
                },
            },
            {
                base: {
                    'border-color': 'var(--color-text-700)',
                    'border-width': '2px',
                    'card-bg': 'var(--color-surface-700)',
                    'card-border-color': 'var(--color-text-700)',
                    'card-border-width': '1px',
                    'card-gap': '0.75rem',
                    'card-hover-bg': 'var(--color-surface-600)',
                    'card-hover-border': 'var(--color-text-600)',
                    'card-padding': '1rem',
                    'card-radius': '0.5rem',
                    'circle-bg': 'var(--color-surface-600)',
                    'circle-size': '1.25rem',
                    'disabled-opacity': '0.5',
                    gap: '0.5rem',
                    'icon-color': 'var(--color-text-50)',
                    'icon-size': '0.5rem',
                    'indicator-color': 'var(--color-text-50)',
                    'indicator-scale': '0',
                    'indicator-scale-selected': '1',
                    'indicator-size': '0.5rem',
                    'invalid-border': 'var(--color-danger-500)',
                    'label-color': 'var(--color-text-500)',
                    'label-size': '0.875rem',
                    'longpress-progress': '0',
                    'segmented-fg': 'var(--color-text-500)',
                    'segmented-font-size': '0.875rem',
                    'segmented-font-weight': '500',
                    'segmented-hover-bg': 'var(--color-surface-600)',
                    'segmented-px': '1rem',
                    'segmented-py': '0.5rem',
                    'segmented-radius': '0.375rem',
                    'segmented-selected-shadow': '0 1px 2px rgb(0 0 0 / 0.1)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                },
                colorInherit: 'radio-group',
                colorSlots: {
                    'card-selected-bg': '100',
                    'card-selected-border': '500',
                    'indicator-color': '500',
                    'segmented-selected-bg': '500',
                    'segmented-selected-fg': 'text-on',
                    'selected-bg': '500',
                    'selected-border': '500',
                },
                longpress: {
                    animation: 'pulse 1s ease-in-out infinite',
                    background:
                        'conic-gradient(from 0deg, var(--focus-ring-color) calc(var(--radio-longpress-progress) * 360deg), transparent 0deg)',
                    'border-radius': '50%',
                    content: "''",
                    inset: '-4px',
                    opacity: '0.5',
                    'pointer-events': 'none',
                    position: 'absolute',
                },
                name: 'radio',
                sizes: {
                    lg: {
                        'card-padding': '1.25rem',
                        'circle-size': '1.5rem',
                        'icon-size': '0.625rem',
                        'indicator-size': '0.625rem',
                        'label-size': '1rem',
                        'segmented-font-size': '1rem',
                        'segmented-px': '1.25rem',
                        'segmented-py': '0.625rem',
                    },
                    md: {},
                    sm: {
                        'card-padding': '0.75rem',
                        'circle-size': '1rem',
                        'icon-size': '0.375rem',
                        'indicator-size': '0.375rem',
                        'label-size': '0.75rem',
                        'segmented-font-size': '0.75rem',
                        'segmented-px': '0.75rem',
                        'segmented-py': '0.375rem',
                    },
                },
            },
            {
                base: {
                    bg: 'var(--color-surface-600)',
                    'border-color': 'var(--color-text-800)',
                    'border-width': '1px',
                    'disabled-opacity': '0.5',
                    fg: 'var(--color-text-500)',
                    'font-size': '0.875rem',
                    'font-weight': '500',
                    gap: '0.5rem',
                    height: '2.5rem',
                    'icon-color': 'var(--color-text-600)',
                    'icon-size': '1rem',
                    'invalid-border': 'var(--color-danger-500)',
                    'item-badge-bg': 'var(--color-primary-500)',
                    'item-badge-fg': 'var(--color-text-50)',
                    'item-badge-font-size': '0.625rem',
                    'item-badge-max': '99',
                    'item-badge-min-width': '1.25rem',
                    'item-badge-padding-x': '0.375rem',
                    'item-badge-radius': '0.625rem',
                    'item-description-fg': 'var(--color-text-600)',
                    'item-description-font-size': '0.75rem',
                    'item-disabled-opacity': '0.5',
                    'item-fg': 'var(--color-text-500)',
                    'item-font-size': '0.875rem',
                    'item-gap': '0.5rem',
                    'item-height': '2.25rem',
                    'item-icon-size': '1rem',
                    'item-px': '0.75rem',
                    'item-radius': '0.375rem',
                    'listbox-bg': 'var(--color-surface-700)',
                    'listbox-border-color': 'var(--color-surface-600)',
                    'listbox-border-width': '1px',
                    'listbox-max-height': '16rem',
                    'listbox-padding': '0.25rem',
                    'listbox-radius': '0.5rem',
                    'listbox-shadow': '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'placeholder-color': 'var(--color-text-700)',
                    'popover-animation-offset': '0.5rem',
                    'popover-animation-scale': '0.95',
                    'popover-offset': '4',
                    px: '0.75rem',
                    radius: '0.5rem',
                    'section-header-fg': 'var(--color-text-700)',
                    'section-header-font-size': '0.75rem',
                    'section-header-font-weight': '600',
                    'section-header-px': '0.75rem',
                    'section-header-py': '0.5rem',
                    'separator-color': 'var(--color-surface-600)',
                    'separator-height': '1px',
                    'separator-my': '0.25rem',
                    shadow: '0 1px 2px rgb(0 0 0 / 0.05)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                    width: 'auto',
                },
                colorSlots: {
                    'hover-bg': 'hovered',
                    'hover-border': 'hovered',
                    'item-focused-bg': '100',
                    'item-hover-bg': '100',
                    'item-pressed-bg': '200',
                    'item-selected-bg': '500',
                    'item-selected-fg': 'text-on',
                    'pressed-bg': 'pressed',
                },
                name: 'select',
                sizes: {
                    lg: { 'font-size': '1rem', height: '3rem', 'item-height': '2.5rem', px: '1rem' },
                    md: {},
                    sm: { 'font-size': '0.75rem', height: '2rem', 'item-height': '1.75rem', px: '0.5rem' },
                },
            },
            {
                base: {
                    gap: '0',
                    'list-bg': 'var(--color-surface-700)',
                    'list-border-color': 'transparent',
                    'list-border-width': '0',
                    'list-gap': '0.25rem',
                    'list-padding': '0.25rem',
                    'list-radius': '0.5rem',
                    'panel-padding': '1rem',
                    'tab-badge-bg': 'var(--color-danger-500)',
                    'tab-badge-fg': 'var(--color-text-50)',
                    'tab-badge-font-size': '0.625rem',
                    'tab-badge-font-weight': '600',
                    'tab-badge-min-width': '1.25rem',
                    'tab-badge-padding-x': '0.375rem',
                    'tab-badge-radius': '0.625rem',
                    'tab-bg': 'transparent',
                    'tab-disabled-opacity': '0.5',
                    'tab-fg': 'var(--color-text-600)',
                    'tab-font-size': '0.875rem',
                    'tab-font-weight': '500',
                    'tab-gap': '0.5rem',
                    'tab-height': '2.25rem',
                    'tab-icon-size': '1rem',
                    'tab-px': '1rem',
                    'tab-radius': '0.375rem',
                    'tab-transition-duration': '150ms',
                    'tab-transition-easing': 'ease-out',
                },
                colorSlots: { 'tab-hover-bg': '100', 'tab-selected-bg': '500', 'tab-selected-fg': 'text-on' },
                focusRing: { offset: '0' },
                name: 'tabs',
                sizes: {
                    lg: { 'tab-font-size': '1rem', 'tab-height': '2.75rem', 'tab-px': '1.25rem' },
                    md: {},
                    sm: { 'tab-font-size': '0.75rem', 'tab-height': '1.75rem', 'tab-px': '0.75rem' },
                },
            },
            {
                base: {
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    'item-badge-bg': 'var(--color-primary-500)',
                    'item-badge-fg': 'var(--color-text-50)',
                    'item-badge-font-size': '0.625rem',
                    'item-badge-max': '99',
                    'item-badge-min-width': '1.25rem',
                    'item-badge-padding-x': '0.375rem',
                    'item-badge-radius': '0.625rem',
                    'item-destructive-fg': 'var(--color-danger-500)',
                    'item-destructive-hover-bg': 'var(--color-danger-100)',
                    'item-disabled-opacity': '0.5',
                    'item-fg': 'var(--color-text-500)',
                    'item-font-size': '0.875rem',
                    'item-gap': '0.5rem',
                    'item-height': '2rem',
                    'item-icon-size': '1rem',
                    'item-longpress-haptic-duration': '200',
                    'item-longpress-threshold': '500',
                    'item-px': '0.75rem',
                    'item-radius': '0.375rem',
                    padding: '0.25rem',
                    'popover-animation-offset': '0.5rem',
                    'popover-animation-scale': '0.95',
                    'popover-offset': '4px',
                    radius: '0.5rem',
                    'section-header-fg': 'var(--color-text-700)',
                    'section-header-font-size': '0.75rem',
                    'section-header-font-weight': '600',
                    'section-header-px': '0.75rem',
                    'section-header-py': '0.5rem',
                    'separator-color': 'var(--color-surface-600)',
                    'separator-height': '1px',
                    'separator-my': '0.25rem',
                    shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'shortcut-fg': 'var(--color-text-700)',
                    'shortcut-font-size': '0.75rem',
                    'submenu-delay': '200',
                    'submenu-indicator-color': 'var(--color-text-600)',
                    'submenu-indicator-size': '1rem',
                    'submenu-offset': '4',
                    'submenu-skeleton-bg': 'var(--color-surface-600)',
                    'submenu-skeleton-count': '3',
                    'submenu-skeleton-gap': '0.25rem',
                    'submenu-skeleton-height': '1.5rem',
                    'submenu-skeleton-radius': '0.25rem',
                },
                colorSlots: {
                    'item-focused-bg': '100',
                    'item-hover-bg': '100',
                    'item-pressed-bg': '200',
                    'item-selected-bg': '500',
                    'item-selected-fg': 'text-on',
                },
                name: 'menu',
                sizes: {
                    md: {},
                    sm: { 'item-font-size': '0.75rem', 'item-height': '1.75rem', padding: '0.125rem' },
                },
            },
            {
                base: {
                    'actions-margin-top': '1rem',
                    bg: 'var(--color-surface-700)',
                    'border-color': 'var(--color-surface-600)',
                    'border-width': '1px',
                    'button-cancel-bg': 'var(--color-surface-600)',
                    'button-cancel-fg': 'var(--color-text-500)',
                    'button-confirm-bg': 'var(--color-danger-500)',
                    'button-confirm-fg': 'var(--color-text-50)',
                    'button-gap': '0.5rem',
                    'button-padding-x': '1rem',
                    'button-padding-y': '0.5rem',
                    'button-radius': '0.375rem',
                    'description-fg': 'var(--color-text-600)',
                    'description-margin-top': '0.5rem',
                    fg: 'var(--color-text-500)',
                    'font-size': '0.875rem',
                    'header-font-size': '1rem',
                    'header-font-weight': '600',
                    'max-width': '24rem',
                    'overlay-bg': 'rgb(0 0 0 / 0.5)',
                    padding: '1.5rem',
                    radius: '0.5rem',
                    shadow: '0 8px 16px rgb(0 0 0 / 0.2)',
                    'transition-duration': '150ms',
                    'transition-easing': 'ease-out',
                    'z-index': '100',
                },
                colorSlots: {},
                name: 'confirm-dialog',
                sizes: {},
            },
        ],
        focus: { color: { name: 'primary', step: 400 }, offset: '2px', width: '2px', z: '10' },
        fonts: { mono: 'monospace', ui: 'system-ui' },
        interaction: { announceDuration: 1000, haptic: true, hapticDuration: 200, longPressThreshold: 500 },
        stateShifts: {
            disabled: { alpha: -0.4, chroma: -0.1, hue: 0, lightness: 0 },
            focused: { alpha: 0, chroma: 0.01, hue: 0, lightness: 0.03 },
            hovered: { alpha: 0, chroma: 0, hue: 0, lightness: 0.05 },
            pressed: { alpha: 0, chroma: 0.02, hue: 0, lightness: -0.05 },
            selected: { alpha: 0, chroma: 0.03, hue: 0, lightness: -0.08 },
        },
        tooltipGroup: { boundary: 'viewport', closeDelay: 0, openDelay: 300, timeout: 200 },
        tooltipStyles: [
            {
                arrow: {
                    color: 'var(--tooltip-bg)',
                    height: '7px',
                    staticOffset: '8px',
                    tipRadius: '1px',
                    width: '14px',
                },
                base: {
                    bg: 'var(--color-surface-800)',
                    'border-color': 'transparent',
                    'border-width': '0',
                    fg: 'var(--color-text-50)',
                    'font-size': '0.875rem',
                    'max-width': '20rem',
                    'padding-x': '0.75rem',
                    'padding-y': '0.5rem',
                    radius: '0.375rem',
                    shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'z-index': '50',
                },
                name: 'default',
                transition: {
                    duration: '150ms',
                    easing: 'ease-out',
                    initialOpacity: '0',
                    initialTransform: 'translateY(-4px) scale(0.98)',
                },
            },
            {
                arrow: {
                    color: 'var(--color-danger-600)',
                    height: '7px',
                    stroke: 'var(--color-danger-800)',
                    strokeWidth: '1px',
                    width: '14px',
                },
                base: {
                    bg: 'var(--color-danger-600)',
                    'border-color': 'var(--color-danger-800)',
                    'border-width': '1px',
                    fg: 'var(--color-text-50)',
                    'font-size': '0.875rem',
                    'max-width': '20rem',
                    'padding-x': '0.75rem',
                    'padding-y': '0.5rem',
                    radius: '0.375rem',
                    shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
                    'z-index': '50',
                },
                name: 'error',
                transition: {
                    duration: '120ms',
                    easing: 'ease-in-out',
                    initialOpacity: '0',
                    initialTransform: 'scale(0.95)',
                },
            },
        ],
    },
} as const);

// --- [ENTRY_POINT] -----------------------------------------------------------

const baseConfig = Effect.runSync(
    createConfig({
        mode: 'app',
        name: B.app.name,
        port: B.app.port,
        root: APP_ROOT,
    }),
);
export default defineConfig({
    ...baseConfig,
    plugins: [
        defineTheme(B.theme as unknown as ThemeConfig, ['src/main.css']),
        ...devtoolsPlugin({ app: B.app.name }),
        ...(baseConfig.plugins ?? []),
    ],
});
