name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              <!-- AGENT_CONTEXT
              {"type":"bug","agents":["testing-specialist","typescript-advanced"],"patterns":["effect-pipeline","option-monad"],"priority_hint":"medium"}
              -->
              **Agent-parseable bug report.** All fields map to JSON keys via `id` attribute.

    - type: checkboxes
      id: existing_search
      attributes:
          label: Existing Issues
          description: Confirm you've searched for duplicates
          options:
              - label: I have searched existing issues and this is a new bug
                required: true

    - type: textarea
      id: description
      attributes:
          label: Bug Description
          description: Clear, concise description of the bug
          placeholder: "When [action], [unexpected result] occurs instead of [expected result]"
      validations:
          required: true

    - type: textarea
      id: repro_steps
      attributes:
          label: Steps to Reproduce
          description: Minimal steps to reproduce the bug
          placeholder: |
              1. Navigate to '...'
              2. Click '...'
              3. Observe error
      validations:
          required: true

    - type: textarea
      id: expected_behavior
      attributes:
          label: Expected Behavior
          description: What should happen?
      validations:
          required: true

    - type: textarea
      id: actual_behavior
      attributes:
          label: Actual Behavior
          description: What actually happens?
      validations:
          required: true

    - type: dropdown
      id: severity
      attributes:
          label: Severity
          description: Impact level of this bug
          options:
              - critical
              - high
              - medium
              - low
      validations:
          required: true

    - type: dropdown
      id: scope
      attributes:
          label: Affected Areas
          description: Which areas are affected?
          multiple: true
          options:
              - ui
              - api
              - build
              - types
              - testing
              - config
      validations:
          required: true

    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Runtime environment details
          placeholder: |
              node: 25.2.1
              browser: Chrome 131
              os: macOS 15.1
          render: yaml
      validations:
          required: false

    - type: textarea
      id: logs
      attributes:
          label: Error Logs
          description: Relevant error messages or stack traces
          render: shell
      validations:
          required: false

    - type: input
      id: affected_packages
      attributes:
          label: Affected Packages
          description: Comma-separated list of affected Nx packages
          placeholder: "@parametric/ui, @parametric/core"
      validations:
          required: false
