name: Documentation
description: Create or update documentation
title: "[Docs]: "
labels: ["docs"]
body:
    - type: markdown
      attributes:
          value: |
              <!-- AGENT_CONTEXT
              {"type":"docs","agents":["documentation-specialist"],"patterns":[],"priority_hint":"low"}
              -->
              **Agent-parseable documentation request.** All fields map to JSON keys via `id` attribute.

    - type: dropdown
      id: documentation_type
      attributes:
          label: Documentation Type
          description: What type of documentation change?
          options:
              - new-documentation
              - update-existing
              - fix-error
              - improve-clarity
              - add-examples
              - api-reference
      validations:
          required: true

    - type: input
      id: target_file
      attributes:
          label: Target File
          description: Path to documentation file
          placeholder: "docs/AUTOMATION.md, README.md, REQUIREMENTS.md"
      validations:
          required: true

    - type: textarea
      id: current_content
      attributes:
          label: Current Content
          description: What currently exists (if updating)
          placeholder: "Quote or describe the current documentation state"
      validations:
          required: false

    - type: textarea
      id: proposed_content
      attributes:
          label: Proposed Content
          description: What should the documentation say?
          placeholder: |
              ## Section Title

              Description of the feature...

              ### Example
              ```typescript
              // Code example
              ```
      validations:
          required: true

    - type: textarea
      id: rationale
      attributes:
          label: Rationale
          description: Why is this documentation change needed?
          placeholder: "Users have reported confusion about [topic], this clarifies [aspect]"
      validations:
          required: true

    - type: dropdown
      id: scope
      attributes:
          label: Documentation Scope
          description: Which areas does this documentation cover?
          multiple: true
          options:
              - api-reference
              - architecture
              - getting-started
              - patterns
              - workflows
              - tooling
              - contributing
      validations:
          required: true

    - type: checkboxes
      id: related_files
      attributes:
          label: Cross-Reference Updates
          description: Other files that may need updating
          options:
              - label: REQUIREMENTS.md
              - label: AGENTS.md
              - label: CLAUDE.md
              - label: docs/AUTOMATION.md
              - label: docs/AGENTIC-INFRASTRUCTURE.md
