name: Feature Request
description: Propose a new feature or capability
title: "[Feature]: "
labels: ["feature"]
body:
    - type: markdown
      attributes:
          value: |
              <!-- AGENT_CONTEXT
              {"type":"feature","agents":["library-planner","typescript-advanced"],"patterns":["effect-pipeline","option-monad","branded-types","dispatch-table"],"priority_hint":"medium"}
              -->
              **Agent-parseable feature request.** All fields map to JSON keys via `id` attribute.

    - type: textarea
      id: problem_statement
      attributes:
          label: Problem Statement
          description: What problem does this feature solve?
          placeholder: "Users currently cannot [action] because [limitation], resulting in [negative outcome]"
      validations:
          required: true

    - type: textarea
      id: proposed_solution
      attributes:
          label: Proposed Solution
          description: Your ideal implementation
      validations:
          required: true

    - type: textarea
      id: alternatives_considered
      attributes:
          label: Alternatives Considered
          description: What alternatives have you explored?
      validations:
          required: false

    - type: dropdown
      id: scope
      attributes:
          label: Scope
          description: Which areas does this feature affect?
          multiple: true
          options:
              - ui
              - api
              - build
              - types
              - testing
              - config
      validations:
          required: true

    - type: dropdown
      id: effort_estimate
      attributes:
          label: Estimated Effort
          description: How much work is this?
          options:
              - trivial
              - small
              - medium
              - large
      validations:
          required: false

    - type: textarea
      id: acceptance_criteria
      attributes:
          label: Acceptance Criteria
          description: How will we know this feature is complete?
          placeholder: |
              - [ ] Criterion 1
              - [ ] Criterion 2
              - [ ] Tests pass with 80% coverage
      validations:
          required: true

    - type: checkboxes
      id: required_patterns
      attributes:
          label: Required Patterns
          description: Which architectural patterns apply?
          options:
              - label: effect-pipeline
              - label: option-monad
              - label: branded-types
              - label: dispatch-table
              - label: single-b-constant

    - type: dropdown
      id: breaking_change
      attributes:
          label: Breaking Change
          description: Does this introduce breaking changes?
          options:
              - "no"
              - "yes"
      validations:
          required: true
