name: Feature Request
description: Propose a new feature or capability
title: "[FEAT]: "
labels: ["feat"]
body:
    - type: textarea
      id: description
      attributes:
          label: Problem Statement
          description: What problem does this feature solve?
          placeholder: "Users currently cannot [action] because [limitation]"
      validations:
          required: true

    - type: input
      id: target
      attributes:
          label: Target
          description: Package or area for this feature
          placeholder: "@parametric/ui, src/lib/, new package"
      validations:
          required: true

    - type: textarea
      id: proposed_solution
      attributes:
          label: Proposed Solution
          description: How should this work?
      validations:
          required: true

    - type: textarea
      id: acceptance_criteria
      attributes:
          label: Acceptance Criteria
          description: How will we know this is complete?
          placeholder: |
              - [ ] Criterion 1
              - [ ] Criterion 2
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          options:
              - low
              - medium
              - high
              - critical
      validations:
          required: true

    - type: dropdown
      id: breaking
      attributes:
          label: Breaking Change
          options:
              - "no"
              - "yes"
      validations:
          required: true
