name: Optimize
description: Improve performance or code efficiency
title: "[Optimize]: "
labels: ["optimize"]
body:
    - type: markdown
      attributes:
          value: |
              <!-- AGENT_CONTEXT
              {"type":"optimize","agents":["performance-analyst","cleanup-specialist"],"patterns":["effect-pipeline"],"priority_hint":"low"}
              -->
              **Agent-parseable optimization request.** All fields map to JSON keys via `id` attribute.

    - type: dropdown
      id: optimization_type
      attributes:
          label: Optimization Type
          description: What type of optimization is this?
          options:
              - bundle-size
              - runtime-performance
              - build-time
              - memory-usage
              - code-density
              - tree-shaking
      validations:
          required: true

    - type: input
      id: target_area
      attributes:
          label: Target Area
          description: File, package, or system to optimize
          placeholder: "@parametric/ui bundle, src/lib/heavy-computation.ts"
      validations:
          required: true

    - type: textarea
      id: current_metrics
      attributes:
          label: Current Metrics
          description: Baseline performance measurements
          placeholder: |
              bundle_size_gzip: 312KB
              initial_load_time: 2.4s
              lighthouse_performance: 78
          render: yaml
      validations:
          required: true

    - type: textarea
      id: target_metrics
      attributes:
          label: Target Metrics
          description: Desired performance goals
          placeholder: |
              bundle_size_gzip: <250KB
              initial_load_time: <1.5s
              lighthouse_performance: >90
          render: yaml
      validations:
          required: true

    - type: textarea
      id: proposed_approach
      attributes:
          label: Proposed Approach
          description: How will you achieve these improvements?
          placeholder: |
              - Implement code splitting for routes
              - Replace moment.js with date-fns
              - Enable tree-shaking for lodash
      validations:
          required: true

    - type: dropdown
      id: scope
      attributes:
          label: Scope
          description: Which areas are affected?
          multiple: true
          options:
              - ui
              - api
              - build
              - types
              - runtime
      validations:
          required: true

    - type: textarea
      id: acceptance_criteria
      attributes:
          label: Acceptance Criteria
          description: How will we verify optimization success?
          placeholder: |
              - [ ] Bundle size reduced by X%
              - [ ] No regression in functionality
              - [ ] Lighthouse score improved
      validations:
          required: true

    - type: dropdown
      id: breaking_change
      attributes:
          label: Breaking Change
          description: Does this introduce breaking changes?
          options:
              - "no"
              - "yes"
      validations:
          required: true
