name: Task
description: Work unit that leads to code changes
title: "[TASK]: "
labels: ["kind:task", "status:triage"]
body:
    - type: markdown
      attributes:
          value: |
              <!-- ai-meta
              kind: task
              project_id: 
              phase: 
              status: triage
              agent: 
              effort: 
              -->

    - type: input
      id: project_id
      attributes:
          label: Parent Project ID
          description: Link to parent project (if applicable)
          placeholder: "agentic-framework-001"
      validations:
          required: false

    - type: textarea
      id: objective
      attributes:
          label: Objective
          description: What needs to be accomplished?
          placeholder: "Implement feature X that allows..."
      validations:
          required: true

    - type: textarea
      id: context
      attributes:
          label: Context
          description: Background, related issues, design decisions
          placeholder: "This builds on #123. We need this to support..."
      validations:
          required: false

    - type: input
      id: target
      attributes:
          label: Target
          description: Package, file, or area affected
          placeholder: "@parametric/ui, src/lib/utils.ts, new package"
      validations:
          required: true

    - type: textarea
      id: acceptance_criteria
      attributes:
          label: Acceptance Criteria
          description: Specific, testable conditions for completion
          placeholder: |
              - [ ] Feature X works with input Y
              - [ ] Tests pass with 80%+ coverage
              - [ ] Documentation updated
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          options:
              - "low"
              - "medium"
              - "high"
              - "critical"
          default: 1
      validations:
          required: true

    - type: dropdown
      id: agent
      attributes:
          label: Assigned Agent
          description: Which agent should implement this?
          options:
              - "human"
              - "claude"
              - "copilot"
              - "gemini"
              - "codex"
          default: 0
      validations:
          required: false

    - type: input
      id: effort
      attributes:
          label: Estimated Effort (story points)
          description: Rough estimate of complexity (Fibonacci scale)
          placeholder: "3"
      validations:
          required: false

    - type: textarea
      id: technical_notes
      attributes:
          label: Technical Notes
          description: Implementation hints, constraints, dependencies
          placeholder: |
              - Use Effect pipelines for async operations
              - Follow B constant pattern
              - Add dispatch table for polymorphic behavior
      validations:
          required: false
