# --- API SECRETS TEMPLATE -----------------------------------------------------
# This file documents required secrets. Do NOT commit actual values.
# Use SealedSecrets workflow: mise run seal-secret api-secrets parametric-portal
#
# Required environment variables before running seal-secret:
#   export POSTGRES_USER="app"
#   export POSTGRES_PASSWORD="<db-password>"
#   export ENCRYPTION_KEY="<base64-32-byte-key>"
#   export ANTHROPIC_API_KEY="sk-ant-..."
#   export OAUTH_GITHUB_CLIENT_ID="..."
#   export OAUTH_GITHUB_CLIENT_SECRET="..."
#   export OAUTH_GOOGLE_CLIENT_ID="..."
#   export OAUTH_GOOGLE_CLIENT_SECRET="..."
#   export OAUTH_MICROSOFT_CLIENT_ID="..."
#   export OAUTH_MICROSOFT_CLIENT_SECRET="..."
#
# Output: infrastructure/overlays/prod/sealed-api-secrets.yaml
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  POSTGRES_USER: "<REPLACE_VIA_SEALED_SECRETS>"
  POSTGRES_PASSWORD: "<REPLACE_VIA_SEALED_SECRETS>"
  ENCRYPTION_KEY: "<REPLACE_VIA_SEALED_SECRETS>"
  ANTHROPIC_API_KEY: "<REPLACE_VIA_SEALED_SECRETS>"
  OAUTH_GITHUB_CLIENT_ID: "<REPLACE_VIA_SEALED_SECRETS>"
  OAUTH_GITHUB_CLIENT_SECRET: "<REPLACE_VIA_SEALED_SECRETS>"
  OAUTH_GOOGLE_CLIENT_ID: "<REPLACE_VIA_SEALED_SECRETS>"
  OAUTH_GOOGLE_CLIENT_SECRET: "<REPLACE_VIA_SEALED_SECRETS>"
  OAUTH_MICROSOFT_CLIENT_ID: "<REPLACE_VIA_SEALED_SECRETS>"
  OAUTH_MICROSOFT_CLIENT_SECRET: "<REPLACE_VIA_SEALED_SECRETS>"
