# --- POD DISRUPTION BUDGETS ---------------------------------------------------
# HA guarantees during voluntary disruptions
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: icons-pdb
  labels:
    app.kubernetes.io/name: icons
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: icons
