name: Normalize Commit
description: Transform [TYPE!]: to type!: format for Nx release compatibility

runs:
    using: composite
    steps:
        - name: Transform to conventional commit
          shell: bash
          run: |
              SUBJECT=$(git log -1 --pretty=%s)
              BODY=$(git log -1 --pretty=%b)

              # Extract pattern from schema.ts (single source of truth)
              PATTERN=$(npx tsx -e "import { B } from './.github/scripts/schema.ts'; console.log(B.pr.bash)")
              if [[ -z "$PATTERN" ]]; then
                echo "::error::Failed to extract commit pattern from schema.ts"
                exit 1
              fi

              if [[ "$SUBJECT" =~ $PATTERN ]]; then
                TYPE="${BASH_REMATCH[1]}"
                BREAKING="${BASH_REMATCH[2]}"
                DESC="${BASH_REMATCH[3]}"

                # Convert TYPE to lowercase for conventional commit format
                LOWER_TYPE=$(echo "$TYPE" | tr '[:upper:]' '[:lower:]')
                NEW_SUBJECT="${LOWER_TYPE}${BREAKING}: ${DESC}"

                echo "Transforming commit message:"
                echo "  Old: $SUBJECT"
                echo "  New: $NEW_SUBJECT"

                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"

                # Preserve body if present
                if [ -z "$BODY" ]; then
                  git commit --amend -m "$NEW_SUBJECT"
                else
                  git commit --amend -m "$NEW_SUBJECT" -m "$BODY"
                fi

                git push --force-with-lease
                echo "Commit normalized successfully"
              else
                echo "Commit already in conventional format, skipping"
              fi
