name: Nx Setup
description: Nx monorepo caching and affected command configuration

inputs:
    # Local cache configuration
    cache-path:
        description: Path to Nx cache directory
        default: '.nx/cache'
    cache-key-prefix:
        description: Prefix for cache key
        default: 'nx'
    lockfile-path:
        description: Path to lockfile for cache key generation
        default: 'pnpm-lock.yaml'

    # Remote cache (Nx Cloud) - optional
    cloud-access-token:
        description: Nx Cloud access token for remote caching (optional)
        required: false

    # Affected command setup
    set-shas:
        description: Set NX_BASE and NX_HEAD environment variables for affected commands
        default: 'true'
    main-branch:
        description: Main branch name for affected comparison
        default: 'main'
    workflow-id:
        description: Workflow ID for finding last successful run (uses current workflow if not set)
        required: false

outputs:
    cache-hit:
        description: Whether a cache hit occurred
        value: ${{ steps.cache.outputs.cache-hit }}
    base:
        description: Base SHA for affected commands
        value: ${{ steps.shas.outputs.base }}
    head:
        description: Head SHA for affected commands
        value: ${{ steps.shas.outputs.head }}

runs:
    using: composite
    steps:
        # Local cache via GitHub Actions cache
        - name: Restore Nx cache
          id: cache
          uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
          with:
              path: ${{ inputs.cache-path }}
              key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles(inputs.lockfile-path) }}-${{ github.sha }}
              restore-keys: |
                  ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ hashFiles(inputs.lockfile-path) }}-
                  ${{ runner.os }}-${{ inputs.cache-key-prefix }}-

        # Remote cache via Nx Cloud (optional)
        - name: Configure Nx Cloud
          if: inputs.cloud-access-token != ''
          shell: bash
          run: echo "NX_CLOUD_ACCESS_TOKEN=${{ inputs.cloud-access-token }}" >> $GITHUB_ENV

        # Set base/head SHAs for affected commands
        - name: Set affected SHAs
          id: shas
          if: inputs.set-shas == 'true'
          uses: nrwl/nx-set-shas@dbe0650947e5f2c81f59190a38512cf49126fe6b # v4.3.0
          with:
              main-branch-name: ${{ inputs.main-branch }}
              workflow-id: ${{ inputs.workflow-id }}
