name: Nx Setup
description: Nx monorepo affected command configuration (caching via Nx Cloud)

inputs:
    # Affected command setup
    set-shas:
        description: Set NX_BASE and NX_HEAD environment variables for affected commands
        default: 'true'
    main-branch:
        description: Main branch name for affected comparison
        default: 'main'
    workflow-id:
        description: Workflow ID for finding last successful run (uses current workflow if not set)
        required: false

outputs:
    base:
        description: Base SHA for affected commands
        value: ${{ steps.shas.outputs.base }}
    head:
        description: Head SHA for affected commands
        value: ${{ steps.shas.outputs.head }}

runs:
    using: composite
    steps:
        # Set base/head SHAs for affected commands
        - name: Set affected SHAs
          id: shas
          if: inputs.set-shas == 'true'
          uses: nrwl/nx-set-shas@15514ee4353489ef5a1644bcdae44f0ae2ea45f3 # v4.4.0
          with:
              main-branch-name: ${{ inputs.main-branch }}
              workflow-id: ${{ inputs.workflow-id }}
