name: PR Comment Aggregator
description: Consolidate workflow outputs into single unified PR comment with marker-based update-or-create strategy

inputs:
    pr_number:
        description: Pull request number to comment on
        required: true
    sections_data:
        description: JSON string with section data (changes, affected, quality, biome)
        required: true

outputs:
    comment_id:
        description: ID of the created or updated comment
        value: ${{ steps.comment.outputs.comment_id }}
    comment_url:
        description: URL of the created or updated comment
        value: ${{ steps.comment.outputs.comment_url }}

runs:
    using: composite
    steps:
        - name: Post Unified Comment
          id: comment
          uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
          env:
              NODE_OPTIONS: --import tsx
              SECTIONS_DATA: ${{ inputs.sections_data }}
          with:
              script: |
                  const { run } = await import('${{ github.workspace }}/.github/scripts/pr-comment-aggregator.ts');
                  const data = JSON.parse(process.env.SECTIONS_DATA || '{}');
                  const result = await run({
                      context: { repo: context.repo, payload: context.payload },
                      core,
                      github,
                      spec: {
                          prNumber: parseInt('${{ inputs.pr_number }}', 10),
                          data,
                      },
                  });
                  core.setOutput('comment_id', String(result.id));
                  core.setOutput('comment_url', result.url);
