# --- KYVERNO POLICIES ARGOCD APPLICATION --------------------------------------
# Kyverno policies and exceptions deployed from Git (depends on kyverno Application)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  labels:
    app.kubernetes.io/name: kyverno-policies
    app.kubernetes.io/component: policy-engine
    app.kubernetes.io/part-of: parametric-suite
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/bardiasamiee/Parametric_Portal.git
    targetRevision: HEAD
    path: infrastructure/platform/kyverno

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
