# --- LONGHORN STORAGE PROVIDER ------------------------------------------------
# Distributed block storage for K3s multi-node HA cluster
# Provides ReadWriteOnce + ReadWriteMany PVCs with 3-replica durability
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: longhorn
  namespace: argocd
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: platform
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: longhorn
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform

      source:
        repoURL: https://charts.longhorn.io
        chart: longhorn
        targetRevision: v1.8.1
        helm:
          releaseName: longhorn
          values: |
            # --- [PERSISTENCE] -----------------------------------------------
            persistence:
              defaultClass: true
              defaultFsType: ext4
              defaultClassReplicaCount: 3
              defaultDataLocality: disabled
              reclaimPolicy: Delete

            # --- [STORAGE] ---------------------------------------------------
            defaultSettings:
              # [IMPORTANT] 3-replica minimum for HA durability
              defaultReplicaCount: 3
              # [IMPORTANT] Distributed scheduling across nodes/zones
              replicaSoftAntiAffinity: false
              replicaZoneSoftAntiAffinity: false
              replicaDiskSoftAntiAffinity: false
              # [IMPORTANT] Automatic balance replicas across nodes
              replicaAutoBalance: best-effort
              # [IMPORTANT] Storage over-provisioning percentage
              storageOverProvisioningPercentage: 200
              # [IMPORTANT] Minimum available storage (10%)
              storageMinimalAvailablePercentage: 10
              # [IMPORTANT] Upgrade strategy
              upgradeChecker: true
              # [IMPORTANT] Backup target for disaster recovery
              backupTarget: s3://parametric-portal-backups@us-east-1/longhorn
              backupTargetCredentialSecret: longhorn-backup-secret
              # [IMPORTANT] Fast failover on node failure
              nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
              # [IMPORTANT] Auto-salvage volumes
              autoSalvage: true
              # [IMPORTANT] Disable auto-deletion to prevent data loss
              autoDeletePodWhenVolumeDetachedUnexpectedly: false

            # --- [NETWORKING] ------------------------------------------------
            service:
              ui:
                type: ClusterIP
              manager:
                type: ClusterIP

            # --- [RESOURCES] -------------------------------------------------
            longhornManager:
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 256Mi

            longhornDriver:
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi

            longhornUI:
              replicas: 2
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi

            # --- [SECURITY] --------------------------------------------------
            enablePSP: false
            privateRegistry:
              createSecret: false

            # --- [CSI] -------------------------------------------------------
            csi:
              attacherReplicaCount: 3
              provisionerReplicaCount: 3
              resizerReplicaCount: 3
              snapshotterReplicaCount: 3

      destination:
        server: https://kubernetes.default.svc
        namespace: longhorn-system

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas

      revisionHistoryLimit: 10
