# --- METRICS SERVER -----------------------------------------------------------
# Kubernetes metrics server for HPA and resource monitoring
# Official chart: github.com/kubernetes-sigs/metrics-server
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: platform
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: metrics-server
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform

      source:
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        chart: metrics-server
        targetRevision: 3.13.0
        helm:
          releaseName: metrics-server
          values: |
            # --- [REPLICAS] ----------------------------------------------
            replicas: 2

            # --- [RESOURCES] ---------------------------------------------
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi

            # --- [SECURITY] ----------------------------------------------
            securityContext:
              runAsUser: 1000
              runAsNonRoot: true
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

            # --- [RBAC] --------------------------------------------------
            rbac:
              create: true
              pspEnabled: false

            # --- [API_SERVICE] -------------------------------------------
            apiService:
              create: true

            # --- [SERVICE] -----------------------------------------------
            service:
              type: ClusterIP
              port: 443

            # --- [METRICS] -----------------------------------------------
            metrics:
              enabled: true

            # --- [SERVICE_MONITOR] ---------------------------------------
            serviceMonitor:
              enabled: true
              interval: 60s

            # --- [PRIORITY] ----------------------------------------------
            priorityClassName: system-cluster-critical

            # --- [PDB] ---------------------------------------------------
            podDisruptionBudget:
              enabled: true
              minAvailable: 1

      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      revisionHistoryLimit: 10
