# --- MINIO RESOURCES APPLICATION ----------------------------------------------
# MinIO Tenant deployed after MinIO Operator is ready
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio-resources
  namespace: argocd
  labels:
    app.kubernetes.io/name: minio-resources
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: platform
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: minio-resources
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform

      source:
        repoURL: https://github.com/bardiasamiee/Parametric_Portal.git
        targetRevision: HEAD
        path: infrastructure/platform/minio

      destination:
        server: https://kubernetes.default.svc

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      revisionHistoryLimit: 10
