# --- REDIS CACHING LAYER ------------------------------------------------------
# Bitnami Redis with Sentinel for automatic failover
# Chart reference: github.com/bitnami/charts/tree/main/bitnami/redis
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: platform
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
  template:
    metadata:
      name: redis
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: platform

      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: redis
        targetRevision: 20.6.0
        helm:
          releaseName: redis
          values: |
            # --- [ARCHITECTURE] ------------------------------------------
            architecture: replication

            # --- [AUTH] --------------------------------------------------
            auth:
              enabled: true
              sentinel: true
              existingSecret: redis-password
              existingSecretPasswordKey: redis-password

            # --- [MASTER] ------------------------------------------------
            master:
              count: 1
              persistence:
                enabled: true
                storageClass: longhorn
                size: 10Gi
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              containerSecurityContext:
                enabled: true
                runAsUser: 1001
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              pdb:
                create: true
                minAvailable: 1

            # --- [REPLICA] -----------------------------------------------
            replica:
              kind: StatefulSet
              replicaCount: 2
              persistence:
                enabled: true
                storageClass: longhorn
                size: 10Gi
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              containerSecurityContext:
                enabled: true
                runAsUser: 1001
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              pdb:
                create: true
                minAvailable: 1

            # --- [SENTINEL] ----------------------------------------------
            sentinel:
              enabled: true
              quorum: 2
              downAfterMilliseconds: 5000
              failoverTimeout: 10000
              parallelSyncs: 1
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              containerSecurityContext:
                enabled: true
                runAsUser: 1001
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault

            # --- [METRICS] -----------------------------------------------
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
                interval: 60s
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi

            # --- [NETWORK_POLICY] ----------------------------------------
            networkPolicy:
              enabled: true
              allowExternal: false
              ingressNSMatchLabels: {}
              ingressNSPodMatchLabels: {}

      destination:
        server: https://kubernetes.default.svc
        namespace: redis-system

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

      revisionHistoryLimit: 10
