# --- BACKUP OBJECT STORE ------------------------------------------------------
# S3-compatible object store for WAL archiving and base backups
# Requires s3-backup-credentials Secret with ACCESS_KEY_ID and ACCESS_SECRET_KEY
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: parametric-portal-db-on-demand
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: backup
spec:
  method: barmanObjectStore
  cluster:
    name: parametric-portal-db
