# --- S3 BACKUP CREDENTIALS TEMPLATE -------------------------------------------
# This file documents required S3 credentials for CloudNativePG backup.
# Do NOT commit actual values.
#
# Create manually or via kubectl:
#   kubectl create secret generic s3-backup-credentials \
#     --namespace=parametric-portal \
#     --from-literal=ACCESS_KEY_ID="<your-access-key>" \
#     --from-literal=ACCESS_SECRET_KEY="<your-secret-key>"
#
# Or encrypt with SealedSecrets:
#   kubectl create secret generic s3-backup-credentials \
#     --namespace=parametric-portal \
#     --from-literal=ACCESS_KEY_ID="..." \
#     --from-literal=ACCESS_SECRET_KEY="..." \
#     --dry-run=client -o yaml | \
#   kubeseal --cert=/opt/sealed-secrets-cert.pem --format yaml \
#     > infrastructure/overlays/prod/sealed-s3-backup-credentials.yaml
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: backup
type: Opaque
stringData:
  ACCESS_KEY_ID: "<REPLACE_VIA_SEALED_SECRETS>"
  ACCESS_SECRET_KEY: "<REPLACE_VIA_SEALED_SECRETS>"
