# PR Security Gate -- Dependency review, CodeQL v4, Gitleaks, triage, summary
# Demonstrates: multi-job security pipeline, external policy via config-file,
# pull_request_target safe pattern (payload-only, no PR head checkout),
# SARIF upload, env-var indirection, cross-job result aggregation, PR comment upsert.
name: PR Security Gate
on:
  pull_request: { branches: [main] }
  pull_request_target: { types: [labeled] }  # Safe: labeling only, no PR head checkout

permissions: {}

concurrency:
  group: pr-security-${{ github.event.pull_request.number || github.event.number }}
  cancel-in-progress: true

jobs:
  # --- [JOB 1] Dependency vulnerability + license review ---
  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: { contents: read, pull-requests: write }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          fail-on-severity: high
          # config-file: .github/dependency-review-config.yml  # External YAML policy
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 120
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD
          deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0
          comment-summary-in-pr: always
          warn-only: false  # Strict: block merge on violations

  # --- [JOB 2] CodeQL v4 static analysis (Node 24 runtime) ---
  codeql:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions: { contents: read, security-events: write }
    strategy:
      fail-fast: false
      matrix:
        language: [javascript-typescript]  # Extend: python, go, java, etc.
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: github/codeql-action/init@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
        with:
          languages: ${{ matrix.language }}
          # build-mode: none — auto-detected for interpreted languages
      - uses: github/codeql-action/analyze@45cbd0c69e560cd9e7cd7f8c32362050c9b7ded2 # v4.32.2
        with:
          category: codeql-${{ matrix.language }}  # Distinct SARIF per language

  # --- [JOB 3] Pre-merge secret scanning via Gitleaks ---
  secrets-scan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: { contents: read, security-events: write }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { fetch-depth: 0 }  # Full history for diff-based scanning
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: true     # PR comment on findings
          GITLEAKS_ENABLE_SUMMARY: true      # Job summary with leak details
          # GITLEAKS_CONFIG: .gitleaks.toml   # Custom rules + allowlist
          # GITLEAKS_NOTIFY_USER_LIST: @security-team

  # --- [JOB 4] Safe triage via pull_request_target (payload-only) ---
  triage:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: { pull-requests: write }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      # Safe: operates on event payload only — never checks out PR head code
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const pr = context.payload.pull_request;
            const changed = pr.changed_files || 0;
            const label = changed <= 10 ? 'size/S' : changed <= 50 ? 'size/M' : 'size/L';
            await github.rest.issues.addLabels({
              ...context.repo, issue_number: pr.number, labels: [label]
            });

  # --- [JOB 5] Consolidated PR comment + job summary ---
  summary:
    if: always() && github.event_name == 'pull_request'
    needs: [dependency-review, codeql, secrets-scan]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: { pull-requests: write }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          DEP_RESULT: ${{ needs.dependency-review.result }}
          CODEQL_RESULT: ${{ needs.codeql.result }}
          SECRETS_RESULT: ${{ needs.secrets-scan.result }}
        with:
          script: |
            const icon = (r) => ({ success: '+', skipped: '~', failure: 'x', cancelled: '-' }[r] || '?');
            const rows = [
              `| Dependency Review | [${icon(process.env.DEP_RESULT)}] ${process.env.DEP_RESULT} |`,
              `| CodeQL (v4) | [${icon(process.env.CODEQL_RESULT)}] ${process.env.CODEQL_RESULT} |`,
              `| Gitleaks | [${icon(process.env.SECRETS_RESULT)}] ${process.env.SECRETS_RESULT} |`
            ];
            const body = [
              '## Security Gate Results',
              '| Check | Status |', '|---|---|',
              ...rows, '',
              `*Commit: \`${context.sha.slice(0, 8)}\`*`
            ].join('\n');
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, body);
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo, issue_number: context.issue.number
            });
            const marker = '## Security Gate Results';
            const existing = comments.find(c => c.body?.startsWith(marker));
            const params = { ...context.repo, body };
            existing
              ? await github.rest.issues.updateComment({ ...params, comment_id: existing.id })
              : await github.rest.issues.createComment({ ...params, issue_number: context.issue.number });
