# --- CLOUDNATIVEPG CLUSTER ----------------------------------------------------
# PostgreSQL 17 HA cluster with 3 instances for multi-node deployment
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: parametric-portal-db
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:17

  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised

  storage:
    size: 10Gi
    storageClass: longhorn

  postgresql:
    parameters:
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "8MB"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      log_statement: "ddl"
      log_min_duration_statement: "1000"
      # --- MONITORING EXTENSIONS ---
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: "all"
      track_io_timing: "on"
      track_activities: "on"
      track_counts: "on"

    # --- [SYNCHRONOUS_REPLICATION] -----------------------------------------
    synchronous:
      method: any
      number: 1
      syncReplicaElectionConstraint:
        enabled: true
        nodeLabelsAntiAffinity:
          - topology.kubernetes.io/zone
      failoverQuorum: true

  bootstrap:
    initdb:
      database: parametric_portal
      owner: app

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore:
      # destinationPath uses AWS S3 by default; for S3-compatible storage,
      # add endpointURL via Kustomize patch in overlays/prod
      destinationPath: "s3://parametric-portal-backups/postgres/"
      s3Credentials:
        accessKeyId:
          name: s3-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-backup-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "7d"
