# --- PGBOUNCER CONNECTION POOLER ----------------------------------------------
# CloudNativePG Pooler CRD for PgBouncer connection pooling
# Official API: cloudnative-pg.io/documentation/current/connection_pooling
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: parametric-portal-db-pooler
  namespace: parametric-portal
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: connection-pooler
    app.kubernetes.io/part-of: parametric-portal
spec:
  # --- [CLUSTER] -------------------------------------------------------------
  cluster:
    name: parametric-portal-db

  # --- [INSTANCES] -----------------------------------------------------------
  instances: 3

  # --- [TYPE] ----------------------------------------------------------------
  type: rw

  # --- [DEPLOYMENT_STRATEGY] -------------------------------------------------
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # --- [PGBOUNCER] -----------------------------------------------------------
  pgbouncer:
    poolMode: transaction

    parameters:
      max_client_conn: "200"
      default_pool_size: "10"
      reserve_pool_size: "5"
      max_db_connections: "0"
      max_user_connections: "0"
      server_lifetime: "3600"
      server_idle_timeout: "600"
      log_connections: "1"
      log_disconnections: "1"

  # --- [TEMPLATE] ------------------------------------------------------------
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgbouncer
        app.kubernetes.io/component: connection-pooler
    spec:
      containers:
        - name: pgbouncer
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          # [FIX] Container-level security context must be under container spec
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: pgbouncer
              topologyKey: kubernetes.io/hostname
      # Pod-level security context
      securityContext:
        runAsNonRoot: true
        fsGroup: 26
        fsGroupChangePolicy: OnRootMismatch

  # --- [MONITORING] ----------------------------------------------------------
  monitoring:
    enablePodMonitor: true
