# --- POD DISRUPTION BUDGETS ---------------------------------------------------
# minAvailable: 0 allows voluntary disruptions for single-replica base config
# Production overlay with HPA (minReplicas >= 2) can override to minAvailable: 1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-pdb
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: backend
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: icons-pdb
  labels:
    app.kubernetes.io/name: icons
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: icons
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  minAvailable: 0
  selector:
    matchLabels:
      cnpg.io/cluster: parametric-portal-db
