name: Meta Fixer
description: Auto-fix GitHub object metadata (titles, labels, commits) with AI fallback

inputs:
    target:
        description: 'Target: title|label|body|commit|all'
        required: true
    number:
        description: 'Issue/PR number (optional - fixes single item)'
        required: false
    limit:
        description: 'Max items per category (default: 10)'
        required: false
        default: '10'
    anthropic_api_key:
        description: 'Anthropic API key for Claude'
        required: false

outputs:
    fixed:
        description: 'Number of items fixed'
        value: ${{ steps.run.outputs.fixed }}
    provider:
        description: 'Provider used (local|claude|github|none)'
        value: ${{ steps.run.outputs.provider }}
    commit_message:
        description: 'Fixed commit message (when target=commit)'
        value: ${{ steps.run.outputs.commit_message }}

runs:
    using: composite
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              ref: ${{ github.event.pull_request.head.ref || github.ref }}
              fetch-depth: 2

        - uses: ./.github/actions/node-env

        - name: Run Meta Fixer
          id: run
          shell: bash
          env:
              ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
              GITHUB_TOKEN: ${{ github.token }}
              META_TARGET: ${{ inputs.target }}
              META_NUMBER: ${{ inputs.number }}
              META_LIMIT: ${{ inputs.limit }}
              GH_REPO: ${{ github.repository }}
              GH_EVENT: ${{ github.event_name }}
              GH_PR_NUMBER: ${{ github.event.pull_request.number }}
          run: |
              npx tsx .github/scripts/ai-meta-cli.ts

        - name: Amend Commit
          if: inputs.target == 'commit' && steps.run.outputs.fixed != '0' && steps.run.outputs.commit_message != ''
          shell: bash
          run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git commit --amend -m "${{ steps.run.outputs.commit_message }}"
              git push --force-with-lease
