name: PR Hygiene
description: Automate PR review cleanup - resolve outdated threads, respond to reviewers, cleanup owner prompts

inputs:
    pr_number:
        description: 'Pull request number'
        required: true
    owner_logins:
        description: 'Comma-separated list of owner/admin logins whose prompts should be cleaned'
        required: false
        default: ''
    bot_patterns:
        description: 'Comma-separated list of bot mention patterns to detect prompts (default: @claude,@copilot,@gemini,@codex)'
        required: false
        default: '@claude,@copilot,@gemini,@codex'

outputs:
    resolved:
        description: 'Number of review threads resolved'
        value: ${{ steps.run.outputs.resolved }}
    replied:
        description: 'Number of review comments replied to'
        value: ${{ steps.run.outputs.replied }}
    deleted:
        description: 'Number of owner prompts deleted'
        value: ${{ steps.run.outputs.deleted }}

runs:
    using: composite
    steps:
        # Note: Caller must checkout .github before using this action
        - uses: ./.github/actions/node-env
          with:
              node-version-file: package.json

        - name: Run PR Hygiene
          id: run
          uses: actions/github-script@v7
          env:
              NODE_OPTIONS: --import tsx
          with:
              script: |
                  const { run } = await import('${{ github.workspace }}/.github/scripts/pr-hygiene.ts');
                  const ownerLogins = '${{ inputs.owner_logins }}'.split(',').map(s => s.trim()).filter(Boolean);
                  const botPatterns = '${{ inputs.bot_patterns }}'.split(',').map(s => s.trim()).filter(Boolean);
                  const result = await run({
                      context: { repo: context.repo, payload: context.payload },
                      core,
                      github,
                      spec: {
                          prNumber: parseInt('${{ inputs.pr_number }}'),
                          action: 'synchronize',
                          ownerLogins,
                          botPatterns: botPatterns.length > 0 ? botPatterns : undefined,
                      },
                  });
                  core.setOutput('resolved', result.resolved);
                  core.setOutput('replied', result.replied);
                  core.setOutput('deleted', result.deleted);
