name: PR Hygiene
description: Automated PR review cleanup - resolve outdated threads, respond to addressed feedback, cleanup user comments

inputs:
    pr_number:
        description: Pull request number
        required: true

outputs:
    resolved:
        description: Number of review threads resolved
        value: ${{ steps.run.outputs.resolved }}
    replied:
        description: Number of review comments replied to
        value: ${{ steps.run.outputs.replied }}
    minimized:
        description: Number of comments minimized
        value: ${{ steps.run.outputs.minimized }}
    deleted:
        description: Number of user comments deleted
        value: ${{ steps.run.outputs.deleted }}

runs:
    using: composite
    steps:
        - uses: ./.github/actions/node-env

        - id: run
          uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
          env:
              NODE_OPTIONS: --import tsx
          with:
              script: |
                  const { run } = await import('${{ github.workspace }}/.github/scripts/pr-hygiene.ts');
                  const result = await run({
                      context: { repo: context.repo, payload: context.payload },
                      core,
                      github,
                      spec: {
                          prNumber: parseInt('${{ inputs.pr_number }}'),
                          ownerLogins: [],
                      },
                  });
                  core.setOutput('resolved', result.resolved);
                  core.setOutput('replied', result.replied);
                  core.setOutput('minimized', result.minimized);
                  core.setOutput('deleted', result.deleted);
