name: Git Identity
description: Configure git user for commits
inputs:
    name:
        description: Git user name
        default: github-actions[bot]
    email:
        description: Git user email
        default: github-actions[bot]@users.noreply.github.com
runs:
    using: composite
    steps:
        - shell: bash
          env:
              GIT_USER_NAME: ${{ inputs.name }}
              GIT_USER_EMAIL: ${{ inputs.email }}
          run: |
              git config user.name "$GIT_USER_NAME"
              git config user.email "$GIT_USER_EMAIL"
