# Exemplar: Workflow with outdated/deprecated patterns
# Demonstrates stale action versions, deprecated commands, and legacy patterns
# that the best_practice_checks.sh detects as warnings or errors.
# Validate: bash scripts/validate_workflow.sh --check-best-practices examples/outdated-versions.yml
#
# OUTDATED PATTERNS:
#  1. [OUTDATED] actions/checkout@v4 -- current is v6.0.2
#  2. [OUTDATED] actions/setup-node@v4 -- current is v6.2.0
#  3. [OUTDATED] actions/upload-artifact@v3 -- current is v6.0.0 (v3 is EOL)
#  4. [OUTDATED] actions/cache@v4 -- current is v5.0.3
#  5. [OUTDATED] docker/build-push-action@v5 -- current is v6.19.2
#  6. [OUTDATED] docker/setup-buildx-action@v3 -- current is v3.12.0 (SHA-pin it)
#  7. [OUTDATED] docker/login-action@v3 -- current is v3.7.0 (SHA-pin it)
#  8. [OUTDATED] github/codeql-action@v3 -- current is v4.32.2
#  9. [OUTDATED] ::set-output -- removed Oct 2023, use >> $GITHUB_OUTPUT
# 10. [OUTDATED] ::save-state -- removed Oct 2023, use >> $GITHUB_STATE
# 11. [OUTDATED] Node 16 -- EOL Sep 2023, minimum is Node 20

name: Outdated Versions

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: outdated-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }

      # [OUTDATED] Using v4 mutable tag -- current is v6.0.2
      - uses: actions/checkout@v4

      # [OUTDATED] Using v4 mutable tag -- current is v6.2.0
      # [OUTDATED] Node 16 is EOL -- minimum supported is Node 20
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: npm

      - run: npm ci && npm run build

      # [OUTDATED] Using v3 mutable tag -- v3 is EOL, current is v6.0.0
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/

      # [OUTDATED] Using v4 mutable tag -- current is v5.0.3
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      # [OUTDATED] ::set-output removed Oct 2023 -- use >> $GITHUB_OUTPUT
      - name: Set version
        run: echo "::set-output name=version::1.0.0"

      # [OUTDATED] ::save-state removed Oct 2023 -- use >> $GITHUB_STATE
      - name: Save state
        run: echo "::save-state name=backup::true"

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20
    permissions: { contents: read, packages: write }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }

      # [OUTDATED] Mutable tag -- should be SHA-pinned
      - uses: actions/checkout@v4

      # [OUTDATED] Mutable tag -- current is v3.12.0
      - uses: docker/setup-buildx-action@v3

      # [OUTDATED] Mutable tag -- current is v3.7.0
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # [OUTDATED] Using v5 mutable tag -- current is v6.19.2
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  scan:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: { contents: read, security-events: write }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@v4
      # [OUTDATED] Using v3 -- current is v4.32.2 (Node 24 runtime)
      - uses: github/codeql-action/init@v3
        with: { languages: javascript-typescript }
      - uses: github/codeql-action/analyze@v3
