# Example: Workflow with Outdated Action Versions
# Use: bash scripts/validate_workflow.sh --check-versions examples/outdated-versions.yml
#
# VERSION ISSUES:
# 1. actions/checkout@v4 - OUTDATED (current: v6)
# 2. actions/setup-node@v4 - OUTDATED (current: v6)
# 3. actions/upload-artifact@v3 - DEPRECATED (minimum: v4)
# 4. docker/build-push-action@v5 - OUTDATED (current: v6)
# 5. actions/cache@v4 - OUTDATED (current: v5)

name: Workflow with Outdated Versions

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # OUTDATED: Using v4, current is v6
      - name: Checkout code
        uses: actions/checkout@v4

      # OUTDATED: Using v4, current is v6
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and build
        run: |
          npm ci
          npm run build

      # DEPRECATED: Using v3, minimum supported is v4
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/

      # OUTDATED: Using v4, current is v5
      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # OUTDATED: Using v5, current is v6
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
