# Exemplar: Valid CI Workflow -- passes ALL best_practice_checks.sh with ZERO warnings
# Demonstrates: permissions deny-all, per-job minimal grants, harden-runner first step,
# timeout-minutes, concurrency group, SHA-pinned actions with version comments,
# matrix strategy, caching, artifact upload, GITHUB_OUTPUT, GITHUB_STEP_SUMMARY.
# Validate: bash scripts/validate_workflow.sh examples/valid-ci.yml
# Validate: bash scripts/validate_workflow.sh --check-best-practices examples/valid-ci.yml

name: CI
on:
  push:
    branches: [main]
    paths-ignore: ['docs/**', '**/*.md', 'LICENSE']
  pull_request:
    branches: [main]
    paths-ignore: ['docs/**', '**/*.md', 'LICENSE']
  workflow_dispatch:

permissions: {}

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: { NODE_VERSION: '24' }

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: { contents: read }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with: { node-version: '${{ env.NODE_VERSION }}', cache: pnpm }
      - run: corepack enable && pnpm install --frozen-lockfile
      - run: pnpm lint

  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions: { contents: read }
    strategy:
      matrix:
        node-version: ['22', '24']
      fail-fast: false
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with: { node-version: '${{ matrix.node-version }}', cache: pnpm }
      - run: corepack enable && pnpm install --frozen-lockfile
      - name: Run tests
        id: tests
        run: |
          pnpm test -- --reporter=junit --outputFile=test-results/junit.xml
          echo "passed=true" >> "$GITHUB_OUTPUT"
      - if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: test-results/
          retention-days: 7
      - if: always()
        shell: bash
        run: |
          echo "## Test Results (Node ${{ matrix.node-version }})" >> "$GITHUB_STEP_SUMMARY"
          echo "| Metric | Value |" >> "$GITHUB_STEP_SUMMARY"
          echo "|--------|-------|" >> "$GITHUB_STEP_SUMMARY"
          echo "| Status | ${{ steps.tests.outputs.passed && 'Passed' || 'Failed' }} |" >> "$GITHUB_STEP_SUMMARY"

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: { contents: read }
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with: { node-version: '${{ env.NODE_VERSION }}', cache: pnpm }
      - run: corepack enable && pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build-${{ github.sha }}
          path: dist/
          retention-days: 7
          if-no-files-found: error
