# Exemplar: Workflow with intentional violations -- triggers EVERY best_practice_checks.sh check
# Validate: bash scripts/validate_workflow.sh examples/with-errors.yml
# Validate: bash scripts/validate_workflow.sh --check-best-practices examples/with-errors.yml
#
# BEST PRACTICE VIOLATIONS (by check function):
#  1. [PERMISSIONS]    -- No top-level permissions: block
#  2. [UNPINNED]       -- Mutable tag refs (actions/checkout@v4, actions/setup-node@v3)
#  3. [SHA-NO-COMMENT] -- SHA-pinned but missing # vX.Y.Z comment
#  4. [TIMEOUT]        -- Jobs missing timeout-minutes
#  5. [RUNNER]         -- Deprecated runner (ubuntu-20.04)
#  6. [CONCURRENCY]    -- No concurrency group
#  7. [DEPRECATED-CMD] -- Uses ::set-output removed workflow command
#  8. [HARDEN]         -- Missing harden-runner; and not-first-step in second job
#  9. [INJECTION]      -- Direct ${{ github.event.pull_request.title }} in run: block
# 10. [APP-TOKEN]      -- PAT secret for cross-repo ops
# 11. [IMMUTABLE]      -- Action publishing without immutable OCI

name: Workflow with Errors

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# [VIOLATION] No top-level permissions: block -- defaults to read-write
# [VIOLATION] No concurrency: group -- redundant runs waste runner minutes

jobs:
  build:
    name: Build
    # [VIOLATION] Deprecated runner -- ubuntu-20.04 is EOL, use ubuntu-24.04
    runs-on: ubuntu-20.04
    # [VIOLATION] Missing timeout-minutes -- default is 6 hours

    steps:
      # [VIOLATION] No harden-runner as first step (missing entirely in this job)

      # [VIOLATION] Mutable tag ref -- supply chain risk (CVE-2025-30066)
      - uses: actions/checkout@v4

      # [VIOLATION] Mutable tag ref -- v3 is outdated
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm ci && npm run build

      # [VIOLATION] Direct untrusted input in run: block -- shell injection risk
      - name: Log PR title
        run: |
          echo "PR: ${{ github.event.pull_request.title }}"

      # [VIOLATION] Deprecated ::set-output command (removed Oct 2023)
      - name: Set output
        run: echo "::set-output name=result::success"

      # [VIOLATION] PAT for cross-repo ops -- use create-github-app-token instead
      - name: Cross-repo sync
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/org/other/dispatches
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    # [VIOLATION] Missing timeout-minutes

    steps:
      # [VIOLATION] harden-runner present but NOT first step
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with: { egress-policy: audit }

      # [VIOLATION] SHA-pinned but missing version comment (no # vX.Y.Z)
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: deploy-bundle
          path: dist/

      # [VIOLATION] Action publishing without immutable OCI distribution
      - name: Publish action
        run: |
          cp action.yml dist/
          echo "Publishing action..."
