# Dependency Review -- Vulnerability + license scanning on PRs, harden-runner
name: Dependency Review
on:
  pull_request: { branches: [main, develop] }
  workflow_dispatch:

permissions: { contents: read, pull-requests: write }
concurrency:
  group: dep-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.0
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          fail-on-severity: high
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD
          deny-licenses: GPL-3.0, AGPL-3.0, LGPL-3.0
          comment-summary-in-pr: always
