# SBOM Attestation -- Build, scan (Trivy), SBOM (Syft), attest provenance, harden-runner
name: Build and Attest Container Image
on:
  push: { branches: [main], tags: ['v*'] }
  workflow_dispatch:

permissions: { contents: read, packages: write, id-token: write, attestations: write, security-events: write }
concurrency:
  group: sbom-attest-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env: { REGISTRY: ghcr.io, IMAGE_NAME: '${{ github.repository }}' }

jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.0
        with: { egress-policy: audit }
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with: { registry: '${{ env.REGISTRY }}', username: '${{ github.actor }}', password: '${{ secrets.GITHUB_TOKEN }}' }
      - id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
      - id: build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
      - uses: anchore/sbom-action@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2
        with: { image: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}', format: spdx-json, output-file: sbom.spdx.json, upload-artifact: true }
      - uses: actions/attest-sbom@4651f806c01d8637787e274ac3bdf724ef169f34 # v3.0.0
        with: { subject-name: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}', subject-digest: '${{ steps.build.outputs.digest }}', sbom-path: sbom.spdx.json, push-to-registry: true }
      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with: { image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}', format: sarif, output: trivy-results.sarif, severity: 'CRITICAL,HIGH' }
      - if: always()
        uses: github/codeql-action/upload-sarif@46a5d05688af3c0b623936fd3365ef1ae945c1cd # v3.32.2
        with: { sarif_file: trivy-results.sarif, category: container-scan }
      - uses: actions/attest-build-provenance@62fc1d596301d0ab9914e1fec14dc5c8d93f65cd # v3.2.0
        with: { subject-name: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}', subject-digest: '${{ steps.build.outputs.digest }}', push-to-registry: true }
