# --- PROJECT METADATA ---------------------------------------------------------
# Platform configuration for automated resource provisioning
apiVersion: platform.parametric-portal.com/v1alpha1
kind: Project
metadata:
  name: my-project  # CHANGE THIS: lowercase, kebab-case, matches folder name
spec:
  displayName: "My Project"  # CHANGE THIS: human-readable name
  owner: "team-name"  # CHANGE THIS: owning team name

  domain: "myproject.example.com"  # CHANGE THIS: custom domain (BYOD)
  dnsProvider: clouddns  # OPTIONS: clouddns (GCP) | azuredns (Azure)

  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
      storage: "20Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
      pods: "20"

  services:
    database:
      enabled: true  # CHANGE THIS: true to provision database on shared cluster
      name: "my_project_db"  # CHANGE THIS: database name (lowercase, underscore)

    objectStorage:
      enabled: true  # CHANGE THIS: true to provision S3 bucket on MinIO
      bucketName: "my-project-files"  # CHANGE THIS: bucket name (lowercase, hyphen)

    redis:
      enabled: true  # CHANGE THIS: true to provision Redis database slot
      database: 0  # CHANGE THIS: Redis DB number (0-15, unique per project)

  monitoring:
    enabled: true  # CHANGE THIS: false to opt-out of platform monitoring
    dashboards:
      - backend-metrics  # OPTIONAL: custom Grafana dashboard names
      - frontend-metrics
