name: Label Sync

on:
    push:
        branches: [main]
        paths: [".github/labels.yml"]
    pull_request:
        paths: [".github/labels.yml"]

permissions:
    contents: read
    issues: write

jobs:
    sync-labels:
        name: Sync Label Definitions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Sync Labels
              uses: crazy-max/ghaction-github-labeler@de749cf181958193cb7debf1219836ba3d6511c9 # v5
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  yaml-file: .github/labels.yml
                  skip-delete: ${{ github.event_name == 'pull_request' }}
                  dry-run: ${{ github.event_name == 'pull_request' }}
